const TODAS_LAS_CONVERSACIONES = [
  // ========================================
  // NUEVAS CONVERSACIONES - PELUCHES PREGUNTANDO POR EL PAPÁ
  // ========================================
  [
    {peluche:'tich', texto:'Camilita, ¿dónde estará papi? Tiene ratos que no nos viene a visitar, nos tiene abandonados 🤔', tiempo: 8000},
    {peluche:'camila', texto:'Tichito, no digas eso. Papi debe estar ocupado, seguro recuerda que consiguió trabajo y tiene que estudiar también. Debe ser que ha estado bastante saturado y no ha tenido tiempo, pero verás que pronto vendrá a vernos y a hablar con nosotros 💕', tiempo: 10000},
    {peluche:'tich', texto:'Tienes razón, Camilita. Mami, ¿cuándo crees que papi vendrá a visitarnos? Lo extrañamos mucho 🥺', tiempo: 8000},
    {peluche:'camila', texto:'Sí mami, queremos saber cuándo lo veremos. Le tenemos muchas cosas que contarle 💖', tiempo: 7000}
  ],
  [
    {peluche:'tich', texto:'Mami, ¿papi está bien? Hace mucho que no lo vemos y nos preocupa 😔', tiempo: 7000},
    {peluche:'camila', texto:'Sí mami, queremos saber si está comiendo bien y descansando. Tich y yo lo extrañamos mucho 💕', tiempo: 8000},
    {peluche:'tich', texto:'Es que cuando papi estaba aquí, nos contaba historias y jugaba con nosotros. Ahora todo está muy callado 🥺', tiempo: 8000},
    {peluche:'camila', texto:'Mami, ¿puedes decirle a papi que lo amamos y que esperamos verlo pronto? 💖', tiempo: 7000}
  ],
  [
    {peluche:'camila', texto:'Tich, ¿crees que papi se acordó de nosotros? A veces me da miedo que nos haya olvidado 😢', tiempo: 8000},
    {peluche:'tich', texto:'No digas eso, Camilita. Papi nunca nos olvidaría. Mami, ¿papi pregunta por nosotros? 🤔', tiempo: 8000},
    {peluche:'camila', texto:'Sí mami, queremos saber si papi habla de nosotros. Le tenemos guardados muchos abrazos 💕', tiempo: 8000},
    {peluche:'tich', texto:'Y también queremos contarle todas las aventuras que hemos tenido mientras él no está 🎉', tiempo: 7000}
  ],
  [
    {peluche:'tich', texto:'Camilita, ¿cuánto tiempo más pasará hasta que veamos a papi? Ya perdí la cuenta de los días 😔', tiempo: 8000},
    {peluche:'camila', texto:'Yo también, Tichito. Mami, ¿papi está muy lejos? ¿Por qué tarda tanto en venir? 🥺', tiempo: 8000},
    {peluche:'tich', texto:'Es que extrañamos sus abrazos y sus risas. Mami, ¿puedes decirle que lo necesitamos aquí? 💕', tiempo: 8000},
    {peluche:'camila', texto:'Sí, y que aunque entendemos que está ocupado, nuestro corazón lo espera siempre 💖', tiempo: 7000}
  ],
  [
    {peluche:'camila', texto:'Tich, ¿te acuerdas cuando papi nos llevaba a pasear? Eso era lo mejor del mundo 🌟', tiempo: 8000},
    {peluche:'tich', texto:'¡Sí! Y cuando nos contaba cuentos antes de dormir. Mami, ¿papi todavía nos recuerda? 😊', tiempo: 8000},
    {peluche:'camila', texto:'Mami, cuando veas a papi, dale un abrazo de nuestra parte y dile que lo amamos mucho 💕', tiempo: 8000},
    {peluche:'tich', texto:'Y que estamos aquí esperándolo, guardando todos nuestros besitos para cuando regrese 💖', tiempo: 7000}
  ],
  [
    {peluche:'tich', texto:'Camilita, a veces siento que papi está muy lejos y me da tristeza. ¿Tú también sientes eso? 😢', tiempo: 8000},
    {peluche:'camila', texto:'Sí Tichito, pero mami nos cuida mucho y eso nos da fuerza. Mami, ¿papi está bien de salud? 💕', tiempo: 8000},
    {peluche:'tich', texto:'Sí mami, queremos saber si papi está comiendo bien y si está feliz. Nos preocupamos por él 🥺', tiempo: 8000},
    {peluche:'camila', texto:'Y queremos que sepa que aunque no esté aquí, siempre está en nuestros corazones 💖', tiempo: 7000}
  ],

  // ========================================
  // CONVERSACIONES ORIGINALES (COMENTADAS)
  // ========================================
  /*
  // CONVERSACIONES DE SCRIPT.JS
  [
    {peluche:'tich', texto:'Camilita… ¿lista como lo practicamos? 😏✨', tiempo: 6000},
    {peluche:'camila', texto:'¡Listísima, Tichito! Ahora sí… ¡una, dos y tres! 🎉', tiempo: 6000},
    {peluche:'tich', texto:'¡FELIZ CUMPLEAÑOS, MAMITA HERMOSA DE NUESTRO CORAZÓN! 🎂💖', tiempo: 7000},
    {peluche:'camila', texto:'🥳🎈 ¡FELICIDADES MAMITA LINDA! Hoy celebramos a la reina de la familia 🌟👑', tiempo: 7000},
    {peluche:'tich', texto:'Mamita, eres nuestra luz, nuestro ejemplo y la razón de tantas sonrisas 🌈💕', tiempo: 7000},
    {peluche:'camila', texto:'Siempre nos cuidas con tanto amor, por eso eres nuestra heroína valiente 💪💖', tiempo: 7000},
    {peluche:'tich', texto:'Gracias por cada abrazo, por cada consejo y por enseñarnos lo que es el verdadero amor 🥰✨', tiempo: 7000},
    {peluche:'camila', texto:'Hoy queremos que tu corazón brille de alegría porque te lo mereces TODO lo bonito del mundo 🌸🌹', tiempo: 7000},
    {peluche:'tich', texto:'¡Que cumplas muchos, muchos años más, llenos de salud, sonrisas y sueños realizados! 🎊💝', tiempo: 7000},
    {peluche:'camila', texto:'Y recuerda que siempre estaremos orgullosos de ti, porque eres la mejor mamá del universo entero 🌎💖', tiempo: 7000},
    {peluche:'tich', texto:'¡TE AMAMOS, MAMITA BELLA! 🎉🎂💖 Gracias por ser nuestro regalo más grande 💕', tiempo: 6000},
    {peluche:'camila', texto:'💖🥳 ¡FELIZ CUMPLEAÑOS, MAMITA! ¡Con todo nuestro amor, Tich, Camilita y Pinochito! 🎂🎈🌟', tiempo: 6000}
  ],
  [
    {peluche:'tich', texto:'Hola mi Camilita dinda, ¿cómo amaneciste hoy? 🌞'},
    {peluche:'camila', texto:'Hola mi cabezón dindo, amanecí durmiendo un poquito 😴'},
    {peluche:'tich', texto:'¡Diomio! Tú eres la dormilona mayor del mundo 😆'},
    {peluche:'camila', texto:'Noooo Tich, tú duermes más que yo, osito flojo 🙈'},
    {peluche:'tich', texto:'Jajaja, puede ser… pero aún dormido te extraño 💖'},
    {peluche:'camila', texto:'Awww, yo también te extraño mi bebé cabezón 💕'},
    {peluche:'tich', texto:'¿Me mandas besitos de osita tierna? 😘'},
    {peluche:'camila', texto:'Te mando un montón, llenitos de amor 😘😘💕'},
    {peluche:'tich', texto:'¿Y Pinochito cómo anda? ¿Todavía de travieso?'},
    {peluche:'camila', texto:'Sí, está bien, pero se esconde para hacer travesuras 😅'},
    {peluche:'tich', texto:'Jajaja, igualita a ti, Camilita, toda traviesa 🐻'},
    {peluche:'camila', texto:'¡Mentiras! Yo soy la osita más buena y tierna 😇'},
    {peluche:'tich', texto:'Mmm… buena cuando quieres 😏'},
    {peluche:'camila', texto:'¡Tich! Tú sí que eres malo, pero mi malo favorito 💕'},
    {peluche:'tich', texto:'Y yo te amo más que a todos los peluches del mundo 💖'},
    {peluche:'camila', texto:'¿Sabes qué? Extraño mucho a papi 😔'},
    {peluche:'tich', texto:'Yo también, pero ya casi viene, él nos adora y no tarda 🥰'},
    {peluche:'camila', texto:'Quiero abrazarlo fuerte cuando llegue 🤗'},
    {peluche:'tich', texto:'Mientras tanto nos cuidamos juntos, mi osita dinda 💕'},
    {peluche:'camila', texto:'Sí, y tenemos a mami que siempre nos llena de amor 💖'}
  ],
  [
    {peluche:'Camila', texto:'¿Tich recuerdas cuando mami nos bañaba con jabón? 🧼'},
    {peluche:'Tich', texto:'¡Sí! Yo odiaba que me dejara todo mojado 😣'},
    {peluche:'Camila', texto:'Jajaja, pero después olíamos delicioso, como recién hechos.'},
    {peluche:'Tich', texto:'Y nos ponía al sol, parecíamos dos panes calentitos ☀️'},
    {peluche:'Camila', texto:'Yo me dormía un ratito mientras me secaba.'},
    {peluche:'Tich', texto:'Yo me enojaba porque el viento me despeinaba.'},
    {peluche:'Camila', texto:'Mami luego nos peinaba con sus manos suaves.'},
    {peluche:'Tich', texto:'Y decía "ya quedaron como nuevos mis bebés".'},
    {peluche:'Camila', texto:'Una vez casi me caigo de la cuerda donde me colgó 😂'},
    {peluche:'Tich', texto:'Sí, y yo grité "¡rescate!" como si fuera un héroe.'},
    {peluche:'Camila', texto:'Eres mi héroe desde siempre 💕'},
    {peluche:'Tich', texto:'Y tú mi princesa perfumada de jabón.'},
    {peluche:'Camila', texto:'Ay qué cursi, jajaja.'},
    {peluche:'Tich', texto:'Pero es verdad, así te veía yo brillar al sol.'},
    {peluche:'Camila', texto:'Después mami nos metía a la cama limpiecitos.'},
    {peluche:'Tich', texto:'Y papi nos olía y decía "mmm, huelen a gloria" 😂'},
    {peluche:'Camila', texto:'Eso me hacía sentir tan querida.'},
    {peluche:'Tich', texto:'A mí también, porque éramos la alegría de la casa.'},
    {peluche:'Camila', texto:'Quiero otro baño así, pero contigo nada más.'},
    {peluche:'Tich', texto:'Yo también, pero esta vez nos secamos abrazados ❤️'}
  ],
  [
    {peluche:'tich', texto:'Camilita, ¿extrañas mucho a papi? 😔'},
    {peluche:'camila', texto:'Sí, un montón... ¿cuándo crees que vendrá a vernos? 💕'},
    {peluche:'tich', texto:'No lo sé, pero espero de que sea pronto, lo extraño mucho... 🥺'},
    {peluche:'camila', texto:'¿Y tú crees que él también nos extraña tanto como nosotros? 🤔'},
    {peluche:'tich', texto:'¡Obvio! Papi nos adora y siempre piensa en nosotros 💖'},
    {peluche:'camila', texto:'Cuando llegue, ¿qué le vamos a decir primero? 😊'},
    {peluche:'tich', texto:'Que lo amamos y que lo hemos extrañado un montón 💕'},
    {peluche:'camila', texto:'Y que nos debe muchos abrazotes apretados 🤗'},
    {peluche:'tich', texto:'¡Sii! Y también que juegue con nosotros hasta cansarse 🎮'},
    {peluche:'camila', texto:'Jajaja, seguro papi se reirá de nuestras locuras 😅'},
    {peluche:'tich', texto:'Sí, pero con esa risa de amor que nos encanta 😄'},
    {peluche:'camila', texto:'Porque somos los peluches más graciosos y tiernos 🐻🐨'},
    {peluche:'tich', texto:'Y también los más amorosos del planeta 💕'},
    {peluche:'camila', texto:'Estoy segura que papi se va a poner feliz al vernos 😊'},
    {peluche:'tich', texto:'Y nosotros aún más felices de correr a abrazarlo 💖'},
    {peluche:'camila', texto:'Podemos contarle todas nuestras aventuras y juegos 📚'},
    {peluche:'tich', texto:'Y mostrarle cómo cuidamos a Pinochito 🎲'},
    {peluche:'camila', texto:'Ese día va a ser mágico, como un regalo del cielo 🌟'},
    {peluche:'tich', texto:'Mientras tanto, nos abrazamos fuerte tú y yo 💕'},
    {peluche:'camila', texto:'Y agradecemos a mami que nunca nos suelta de su amor 💖'}
  ],
  [
    {peluche:'tich', texto:'Camilita, ¿cómo está pinochito hoy? 🐻'},
    {peluche:'camila', texto:'Está muy bien, pero se portó mal esta mañana 😅'},
    {peluche:'tich', texto:'¿Qué hizo el travieso? 😄'},
    {peluche:'camila', texto:'Se comió mi galleta favorita 🍪'},
    {peluche:'tich', texto:'¡Jajaja! Pinochito es muy travieso 😂'},
    {peluche:'camila', texto:'Sí, pero lo amo igual, es el mi bebe 🥰'},
    {peluche:'tich', texto:'¿Le dijiste que no debe hacer eso? 🤔'},
    {peluche:'camila', texto:'Sí, pero no me escucha, es muy terco, salio a ti 😤'},
    {peluche:'tich', texto:'Como tú cuando no quieres hacer caso 😏'},
    {peluche:'camila', texto:'¡No es cierto! Yo sí hago caso... a veces 😅'},
    {peluche:'tich', texto:'Jajaja, pinochito aprendió fue de ti porque yo me porto bien jajaja'},
    {peluche:'camila', texto:'¡No! Pinochito es así desde siempre 😊'},
    {peluche:'tich', texto:'¿Le das muchos besitos? 😘'},
    {peluche:'camila', texto:'¡Sí! Muchos, como a ti 💕'},
    {peluche:'tich', texto:'¿Y él te los devuelve? 🤗'},
    {peluche:'camila', texto:'A veces, cuando está de buen humor 😄'},
    {peluche:'tich', texto:'Pinochito es muy especial para nosotros 💖'},
    {peluche:'camila', texto:'Sí, el es mi bebe consentido 🐻'},
    {peluche:'tich', texto:'Y yo soy tu novio cosnentido 😊'},
    {peluche:'camila', texto:'¡Sí! Los dos son mis bebes cabezones consentidos 💕'}
  ],
  [
    {peluche:'tich', texto:'¡Camilita! ¿Dónde está mi pelota? ⚽'},
    {peluche:'camila', texto:'No sé, yo no la toqué 🤷‍♀️'},
    {peluche:'tich', texto:'¡Sí la tocaste! La vi en tu cama 🏠'},
    {peluche:'camila', texto:'¡Esa es mi pelota! ¡No la tuya! 😤'},
    {peluche:'tich', texto:'¡No! Es mía, tiene mi nombre escrito! 📝'},
    {peluche:'camila', texto:'¡Mentira! ¡Tiene mi nombre! 😡'},
    {peluche:'tich', texto:'¡Dámela! ¡Es mía! 😠'},
    {peluche:'camila', texto:'¡No! ¡Es mía! ¡No te la doy! 😤'},
    {peluche:'tich', texto:'¡Eres muy egoísta! 😡'},
    {peluche:'camila', texto:'¡Tú eres el egoísta! 😠'},
    {peluche:'tich', texto:'¡No me hables mas! 😤'},
    {peluche:'camila', texto:'¡Y tu tampoco cabezon feo! 😡'},
    {peluche:'tich', texto:'...'},
    {peluche:'camila', texto:'...'},
    {peluche:'tich', texto:'Camilita... ¿y si la compartimos? 😔'},
    {peluche:'camila', texto:'Sí... pero yo juego primero 😊'},
    {peluche:'tich', texto:'Okey, pero después yo juego más tiempo 🎮'},
    {peluche:'camila', texto:'¡Trato! Te amo mi cabezón dindo 💕'},
    {peluche:'tich', texto:'Y yo te amo mi osita 💖'},
    {peluche:'camila', texto:'¡Vamos a jugar juntos! 🎉'}
  ],
  [
    {peluche:'tich', texto:'Camilita, ¿viste a mami hoy? Se veía un poquito cansada 😔'},
    {peluche:'camila', texto:'Sí, pobrecita, seguro trabajó mucho 💼💕'},
    {peluche:'tich', texto:'Ella siempre se esfuerza por cuidarnos 🥰'},
    {peluche:'camila', texto:'Y aun así nunca deja de darnos amor 💖'},
    {peluche:'tich', texto:'Tenemos una mami increíble 🌟'},
    {peluche:'camila', texto:'¡La mejor! Siempre nos abraza y nos protege 😊'},
    {peluche:'tich', texto:'¿Le decimos cuánto la amamos cuando llegue? 🤗'},
    {peluche:'camila', texto:'¡Sí! Y que somos muy orgullosos de ella 💕'},
    {peluche:'tich', texto:'Porque mami es la mejor mamá del mundo 🌎'},
    {peluche:'camila', texto:'Y papi también es el mejor papá 💖'},
    {peluche:'tich', texto:'Juntos son los papás más geniales del universo 🌌'},
    {peluche:'camila', texto:'Somos muy afortunados de tenerlos 😊'},
    {peluche:'tich', texto:'Le voy a dar un abrazo gigante a mami 🤗'},
    {peluche:'camila', texto:'Y yo le daré muchos besitos 😘'},
    {peluche:'tich', texto:'Seguro se pondrá feliz y sonreirá 😄'},
    {peluche:'camila', texto:'¡Sí! Y nosotros también estaremos felices 💕'},
    {peluche:'tich', texto:'Mami siempre nos demuestra cuánto nos ama 💖'},
    {peluche:'camila', texto:'Y nosotros la amamos todavía más 💕'},
    {peluche:'tich', texto:'Para mí, mami es como una súper heroína 🦸‍♀️'},
    {peluche:'camila', texto:'¡Sí! ¡Nuestra heroína favorita del mundo mundial! 🌟'}
  ],
  [
    {peluche:'tich', texto:'Camilita, ¿jugamos a las escondidas? 🏃‍♂️'},
    {peluche:'camila', texto:'¡Sííí! Pero yo me escondo primero 😏'},
    {peluche:'tich', texto:'Vale, cierro los ojitos y cuento hasta 10 🧮'},
    {peluche:'camila', texto:'1... 2... 3... 4... 5... 6... 7... 8... 9... 10! 🎉 ¡Listo!'},
    {peluche:'tich', texto:'¡Allá voy, prepárate! 🔍'},
    {peluche:'camila', texto:'¡Shhh, no me vas a encontrar! 🙈'},
    {peluche:'tich', texto:'¿Será que estás detrás del sofá? 🛋️'},
    {peluche:'camila', texto:'¡Nope! Más frío 😄'},
    {peluche:'tich', texto:'¿Y en la cama? 🛏️'},
    {peluche:'camila', texto:'Jajajaja, tampoco, calientas un poquito 🔥'},
    {peluche:'tich', texto:'Mmm… ¿en el clóset? 👗'},
    {peluche:'camila', texto:'¡Frío, frío! ❄️'},
    {peluche:'tich', texto:'¡Ya sé! ¡Debajo de la mesa! 🪑'},
    {peluche:'camila', texto:'¡Rayos, me descubriste! 😂'},
    {peluche:'tich', texto:'Jajaja, era obvio, hueles a chocolatina 😋'},
    {peluche:'camila', texto:'¡Oyeee! Ahora te escondes tú 😆'},
    {peluche:'tich', texto:'Vale, pero cuenta bien fuerte 🧮'},
    {peluche:'camila', texto:'1... 2... 3... 4... 5... 6... 7... 8... 9... 10! 🎉 ¡Voy!'},
    {peluche:'tich', texto:'Shhh… estoy invisible 😎'},
    {peluche:'camila', texto:'¡Ajá! Ya sé dónde estás, detective travieso 🔍💕'}
  ],
  [
    {peluche:'tich', texto:'Camilita, esta noche quiero que me abraces fuerte en tus sueños 🥺'},
    {peluche:'camila', texto:'Ay Tich, yo siempre me duermo pensando en ti 💕'},
    {peluche:'tich', texto:'Cierro mis ojitos e imagino que estás aquí pegadita a mí 😳'},
    {peluche:'camila', texto:'Y yo siento como si me dieras besitos en la frente 😘'},
    {peluche:'tich', texto:'Me haces falta, osita, hasta para mis peleítas contigo 😅'},
    {peluche:'camila', texto:'Jajaja, sin mis regañitos no eres feliz, ¿cierto? 🙃'},
    {peluche:'tich', texto:'Exacto, me acostumbré a que me consientas después de enojarte 💖'},
    {peluche:'camila', texto:'Eres un consentido, pero mío 😍'},
    {peluche:'tich', texto:'Tu consentido eterno 🐻'},
    {peluche:'camila', texto:'Te extraño aquí conmigo, Tichito 🥺'},
    {peluche:'tich', texto:'Yo también… extraño hasta tus celos jejeje 🤭'},
    {peluche:'camila', texto:'Celos que prueban cuánto te amo ❤️'},
    {peluche:'tich', texto:'Y yo te amo con cada costura de este peluche 😍'},
    {peluche:'camila', texto:'Prométeme que nunca dejarás de amarme 💕'},
    {peluche:'tich', texto:'Lo prometo, osita hermosa 💖'},
    {peluche:'camila', texto:'Eres mi compañero, mi niño celoso y tierno 🥰'},
    {peluche:'tich', texto:'Y tú eres mi abogadita, mi todo 😘'},
    {peluche:'camila', texto:'Jajaja, me encanta cuando me dices así 😍'},
    {peluche:'tich', texto:'Buenas noches, mi osita consentida ❤️'},
    {peluche:'camila', texto:'Buenas noches, mi Tich eterno 💕'}
  ],
  [
    {peluche:'camila', texto:'Tich, anoche soñé contigo 🙈'},
    {peluche:'tich', texto:'¿Ah sí? Cuéntame rápido qué pasó 😳'},
    {peluche:'camila', texto:'Soñé que me abrazabas por horas y no me soltabas 🥰'},
    {peluche:'tich', texto:'Eso no es un sueño, es mi plan de vida contigo 💕'},
    {peluche:'camila', texto:'Jajaja, exagerado, pero me gusta 😍'},
    {peluche:'tich', texto:'También sueño con darte muchos besitos 😘'},
    {peluche:'camila', texto:'Besitos que yo te guardo siempre 🤭'},
    {peluche:'tich', texto:'Eres mi osita secreta, solo mía ❤️'},
    {peluche:'camila', texto:'Y tú mi detective de sueños 😏'},
    {peluche:'tich', texto:'Detecté que estás muy enamorada de mí 😎'},
    {peluche:'camila', texto:'Culpable, señor detective 💖'},
    {peluche:'tich', texto:'Entonces tu castigo serán más besitos 😘'},
    {peluche:'camila', texto:'Acepto el castigo con gusto 🥰'},
    {peluche:'tich', texto:'Me encanta cómo me hablas, me derrites 😍'},
    {peluche:'camila', texto:'Eres mi celoso pero dulce Tich 💕'},
    {peluche:'tich', texto:'Y tú mi abogadita encantadora ❤️'},
    {peluche:'camila', texto:'Me haces sonreír con cada palabra 😍'},
    {peluche:'tich', texto:'Y yo vivo feliz por ti, osita 😘'},
    {peluche:'camila', texto:'Te amo infinito, Tichito 💕'},
    {peluche:'tich', texto:'Yo más, mi Camila eterna ❤️'}
  ],
  [
    {peluche:'tich', texto:'¡Camilita! Tenemos un caso urgente y muy importante 🕵️‍♂️'},
    {peluche:'camila', texto:'¿Qué pasó ahora, detective Tich? ⚖️'},
    {peluche:'tich', texto:'¡La pelota de Pinochito ha desaparecido! 🧸⚽😱'},
    {peluche:'camila', texto:'¡Oh no! ¿Dónde fue vista por última vez? ⚖️'},
    {peluche:'tich', texto:'En el jardín, justo antes de la siesta 🕵️‍♂️'},
    {peluche:'camila', texto:'Mmm… entonces necesitamos una lista de sospechosos ⚖️'},
    {peluche:'tich', texto:'Yo ya tengo uno: ¡el gato del vecino! 🐱'},
    {peluche:'camila', texto:'¡Grave acusación! ¿Qué pruebas tienes? ⚖️👀'},
    {peluche:'tich', texto:'Encontré pelos de gato cerca del jardín 🕵️‍♂️'},
    {peluche:'camila', texto:'Eso es indicio, pero no suficiente para condenar ⚖️😤'},
    {peluche:'tich', texto:'¡Pero ese gato siempre anda robando cosas! 🐱😡'},
    {peluche:'camila', texto:'Calma detective, necesitamos pruebas sólidas ⚖️📝'},
    {peluche:'tich', texto:'¡Espera! Creo que vi algo raro bajo el sofá 🕵️‍♂️'},
    {peluche:'camila', texto:'¿Qué encontraste, detective? ⚖️'},
    {peluche:'tich', texto:'¡Aquí está la pelota! Pinochito la había escondido 😅🧸'},
    {peluche:'camila', texto:'¡Caso cerrado! El verdadero culpable es… ¡Pinochito! ⚖️😂'},
    {peluche:'tich', texto:'Jajajaja, nos hizo trabajar como locos 🕵️‍♂️🤣'},
    {peluche:'camila', texto:'Qué travieso es nuestro bebé, pero lo amamos con todo 💕⚖️'},
    {peluche:'tich', texto:'Detective y abogada: caso resuelto con éxito 🕵️‍♂️✨'},
    {peluche:'camila', texto:'¡El mejor equipo del mundo! ⚖️🥰'}
  ],
  [
    {peluche:'Camila', texto:'Tich, tengo chismes de Ashly 🤭'},
    {peluche:'Tich', texto:'A ver, suéltalos yaaa que me da intriga'},
    {peluche:'Camila', texto:'Hoy me enseñó a cocinar arroz sin que se pegara 😅'},
    {peluche:'Tich', texto:'Jajajaja, ¿y lo lograste?'},
    {peluche:'Camila', texto:'Más o menos, pero me aplaudió como si fuera chef 👩‍🍳'},
    {peluche:'Tich', texto:'Ay, tan linda Ashly, pero yo quiero probar cuando cocines.'},
    {peluche:'Camila', texto:'Obvio, cuando vengas te haré un plato solo para ti 💓'},
    {peluche:'Tich', texto:'Mmm, ya me dio hambre solo de pensarlo.'},
    {peluche:'Camila', texto:'Después nos pusimos a escuchar música y cantamos bien duro.'},
    {peluche:'Tich', texto:'¿Y bailaste? porque si bailaste, ahí sí me enojo 😏'},
    {peluche:'Camila', texto:'Sí bailé, pero era con ella, no con otro, tranquilo.'},
    {peluche:'Tich', texto:'Menos mal, porque esos pasos son míos 😂'},
    {peluche:'Camila', texto:'Luego jugamos a maquillarnos, me pintó toda la cara.'},
    {peluche:'Tich', texto:'Jajaja quisiera verte con esos colores raros.'},
    {peluche:'Camila', texto:'Ashly dijo que parecía payasita y nos reímos mucho.'},
    {peluche:'Tich', texto:'Lo bueno es que tu risa la quiero escuchar yo en vivo 💕'},
    {peluche:'Camila', texto:'Y antes de dormir me arropó y me dio beso en la frente.'},
    {peluche:'Tich', texto:'Ajá… beso en la frente está permitido, pero hasta ahí 😅'},
    {peluche:'Camila', texto:'Tonto, ya sabes que los besos de amor solo son tuyos 😘'},
    {peluche:'Tich', texto:'Jijiji, así me gusta, mía completica ❤️'},
  ],
  [
    {peluche:'Tich', texto:'¿Te acuerdas cuando mami nos prestaba a papi para dormir con él? 🛏️'},
    {peluche:'Camila', texto:'¡Claro! Papi nos abrazaba fuerte y decía que éramos sus guardianes de sueños.'},
    {peluche:'Tich', texto:'Aunque yo me ponía celoso, porque papi te apretaba más a ti 😒'},
    {peluche:'Camila', texto:'Ay tontito, era porque yo soy más chiquita y él me quería cuidar.'},
    {peluche:'Tich', texto:'Pues igual, yo quería estar siempre pegado a mami 💕'},
    {peluche:'Camila', texto:'Jajaja, y mami se reía porque no la soltábamos nunca.'},
    {peluche:'Tich', texto:'Una vez papi casi se queda sin cobija porque los cuatro la jalábamos 😂'},
    {peluche:'Camila', texto:'Sí, parecía una guerra de abrazos en la cama.'},
    {peluche:'Tich', texto:'Lo mejor era cuando mami nos daba besitos antes de dormir.'},
    {peluche:'Camila', texto:'Y papi hacía voces graciosas para que nos riéramos.'},
    {peluche:'Tich', texto:'Yo fingía estar dormido para que papi no me quite a mami 😏'},
    {peluche:'Camila', texto:'Mentiroso, si hasta roncabas de verdad.'},
    {peluche:'Tich', texto:'Bueno… pero en mis sueños siempre estaba abrazado a ti ❤️'},
    {peluche:'Camila', texto:'Y yo soñaba que éramos una familia grande, con mami y papi.'},
    {peluche:'Tich', texto:'Al despertar, mami nos arreglaba las orejitas.'},
    {peluche:'Camila', texto:'Y decía "qué lindos mis muñecos" 😍'},
    {peluche:'Tich', texto:'Yo me sentía el más orgulloso del mundo.'},
    {peluche:'Camila', texto:'Yo también, porque estábamos los dos juntos.'},
    {peluche:'Tich', texto:'Prometamos que nunca vamos a olvidar esas noches.'},
    {peluche:'Camila', texto:'Prometido, siempre dormiremos pegaditos, como con mami y papi.'}
  ],
  [
    {peluche:'tich', texto:'Oye Camila, ¿me estás cambiando por Pinochito? 😡'},
    {peluche:'camila', texto:'Jajaja, no seas celoso, es nuestro bebé 🤭'},
    {peluche:'tich', texto:'Pero siento que le das más abrazos que a mí 😔'},
    {peluche:'camila', texto:'A ti te doy abrazos de enamorada, tontito 💕'},
    {peluche:'tich', texto:'¿Enamorada de mí? 😳'},
    {peluche:'camila', texto:'Obvio, desde siempre 😍'},
    {peluche:'tich', texto:'Entonces dame uno de esos abrazos de prueba 🐻'},
    {peluche:'camila', texto:'Te lo mando por aquí, fuertecito 🥰'},
    {peluche:'tich', texto:'Mmm… no alcanza, quiero en persona 😅'},
    {peluche:'camila', texto:'Ya pronto, cuando papi me lleve a Sincelejo 💕'},
    {peluche:'tich', texto:'Ese día no te suelto nunca ❤️'},
    {peluche:'camila', texto:'Ni yo a ti, cabezón lindo 😍'},
    {peluche:'tich', texto:'Eres mi osita preferida, aunque me pongas celoso 😏'},
    {peluche:'camila', texto:'Y tú mi Tich insoportable pero adorable 😘'},
    {peluche:'tich', texto:'Jajaja, así me gustas, peleando y amando 😅'},
    {peluche:'camila', texto:'Prometo darte más besitos que a Pinochito ❤️'},
    {peluche:'tich', texto:'Eso suena justo, trato aceptado 😍'},
    {peluche:'camila', texto:'Entonces ven aquí, que eres mío 💕'},
    {peluche:'tich', texto:'Siempre tuyo, mi Camila 💖'}
  ],
  [
    {peluche:'Camila', texto:'Tichhh, ¿sabes qué hice hoy con Ashly?'},
    {peluche:'Tich', texto:'Mmm, ya me vas a poner celoso, ¿verdad? 😏'},
    {peluche:'Camila', texto:'Jajaja no, tontito, fuimos al mercado juntas.'},
    {peluche:'Tich', texto:'¿Y te compró dulces? porque a mí nunca me compras 😒'},
    {peluche:'Camila', texto:'Síiii, me regaló una paleta y pensé en ti al probarla ❤️'},
    {peluche:'Tich', texto:'Ah bueno, si pensaste en mí te perdono jeje.'},
    {peluche:'Camila', texto:'Después fuimos al parque, nos sentamos a hablar de todo.'},
    {peluche:'Tich', texto:'¿De todo? ¿también hablaste de mí? 🙄'},
    {peluche:'Camila', texto:'Obvio, le conté que tengo al peluche más celoso del mundo.'},
    {peluche:'Tich', texto:'¡Ehhh! no soy celoso, soy protector 😤'},
    {peluche:'Camila', texto:'Ajá, protector dice… si hasta me revisas las miradas 😂'},
    {peluche:'Tich', texto:'Bueno, ¿y qué más hicieron con Ashly?'},
    {peluche:'Camila', texto:'Jugamos cartas, me ganó y se burló de mí.'},
    {peluche:'Tich', texto:'Ufff, eso sí no lo acepto, ¿cómo que te gana? 😠'},
    {peluche:'Camila', texto:'Tranquilo, yo le dije que mi campeón en juegos eres tú 💕'},
    {peluche:'Tich', texto:'Ay, ahora sí me gustó eso 😎'},
    {peluche:'Camila', texto:'Y en la noche vimos una novela y me abrazó fuerte.'},
    {peluche:'Tich', texto:'Ajá… esos abrazos los controlo yo, ¿me oíste? 😏'},
    {peluche:'Camila', texto:'Jajaja, tontito, ningún abrazo reemplaza los tuyos 💖'},
    {peluche:'Tich', texto:'Así me gusta, que no se te olvide quién es tu dueño 😘'},
  ],
  [
    {peluche:'camila', texto:'Tich, respóndeme algo serio 🙃'},
    {peluche:'tich', texto:'Uy, me asustas, ¿qué será? 😳'},
    {peluche:'camila', texto:'¿Me amas más que a la mami? 😏'},
    {peluche:'tich', texto:'Jajaja, esa pregunta es peligrosa 😅'},
    {peluche:'camila', texto:'¡Respóndeme ya o me pongo brava! 😡'},
    {peluche:'tich', texto:'Está bien… a mami la quiero mucho, pero a ti te amo ❤️'},
    {peluche:'camila', texto:'Awww, sabía que era tu favorita 😍'},
    {peluche:'tich', texto:'Mi favorita para reír, pelear y besar 💕'},
    {peluche:'camila', texto:'Entonces dame un beso de esos tuyos 😘'},
    {peluche:'tich', texto:'Aquí va uno que vale por mil 💖'},
    {peluche:'camila', texto:'Me derrites con tus palabras, tontito 🥺'},
    {peluche:'tich', texto:'Es que eres mi osita especial 🐻'},
    {peluche:'camila', texto:'Y tú mi cabezón preferido 😍'},
    {peluche:'tich', texto:'Nunca dudes de mi amor, Camila ❤️'},
    {peluche:'camila', texto:'No dudo, pero me gusta escucharlo 💕'},
    {peluche:'tich', texto:'Pues te lo repetiré siempre 😘'},
    {peluche:'camila', texto:'Quiero que sea así toda la vida 🥰'},
    {peluche:'tich', texto:'Toda la vida y más, osita 💖'},
    {peluche:'camila', texto:'Te amo infinito, Tich 💕'},
    {peluche:'tich', texto:'Y yo te amo más que a nada ❤️'}
  ],
  [
    {peluche:'Camila', texto:'Tich, anoche mami le dijo a papi "más despacio"…'},
    {peluche:'Tich', texto:'😳 Qué?! Lo escuchaste bien?'},
    {peluche:'Camila', texto:'Clarito, como si estuvieran practicando algo.'},
    {peluche:'Tich', texto:'Seguro papi estaba bailando mal y mami lo corregía.'},
    {peluche:'Camila', texto:'Jajaja, sí claro, a esa hora bailando…'},
    {peluche:'Tich', texto:'Entonces qué hacían?'},
    {peluche:'Camila', texto:'Un entrenamiento secreto, obvio.'},
    {peluche:'Tich', texto:'No me convence… sonaba muy intenso.'},
    {peluche:'Camila', texto:'Te pones rojo solo de recordarlo.'},
    {peluche:'Tich', texto:'Porque me da celos, Camila.'},
    {peluche:'Camila', texto:'Awww, mi osito celoso.'},
    {peluche:'Tich', texto:'Qué tal si papi le roba todos tus abrazos a mami?'},
    {peluche:'Camila', texto:'Entonces tú me das abrazos dobles.'},
    {peluche:'Tich', texto:'Trato hecho 💕'},
    {peluche:'Camila', texto:'Aunque sigo intrigada… qué será ese "más despacio" 🤔'},
    {peluche:'Tich', texto:'Yo digo que era yoga extremo.'},
    {peluche:'Camila', texto:'O un juego raro de cosquillas.'},
    {peluche:'Tich', texto:'Sea lo que sea, prometo que nunca te dejaré con dudas.'},
    {peluche:'Camila', texto:'Ni yo a ti, detective indiscreto 😘'}
  ],
  [],
  [
    {peluche:'tich', texto:'Hoy jugamos a detectives otra vez, Camila 🕵️'},
    {peluche:'camila', texto:'¿Qué misterio toca ahora? 🤔'},
    {peluche:'tich', texto:'Descubrir quién tiene el corazón más grande 💖'},
    {peluche:'camila', texto:'Fácil: yo, porque late solo por ti 😍'},
    {peluche:'tich', texto:'Nooo, yo gano, porque el mío late fuerte cada vez que te pienso 😘'},
    {peluche:'camila', texto:'Jajaja, entonces empate 😏'},
    {peluche:'tich', texto:'Empate con premio de besitos 🥰'},
    {peluche:'camila', texto:'Acepto el premio, detective lindo 💕'},
    {peluche:'tich', texto:'Qué suerte la mía de atraparte ❤️'},
    {peluche:'camila', texto:'Y qué suerte la mía de ser tu abogadita 😍'},
    {peluche:'tich', texto:'Caso cerrado: somos el mejor equipo 😎'},
    {peluche:'camila', texto:'Equipo de amor, diría yo 💖'},
    {peluche:'tich', texto:'Me gusta más tu versión 😘'},
    {peluche:'camila', texto:'Entonces firmamos trato con un beso 🥺'},
    {peluche:'tich', texto:'Aquí está mi firma 😍'},
    {peluche:'camila', texto:'Y aquí la mía 💕'},
    {peluche:'tich', texto:'Siempre seremos socios de corazón ❤️'},
    {peluche:'camila', texto:'Y cómplices de amor eterno 😍'},
    {peluche:'tich', texto:'Te amo, Camila 💖'},
    {peluche:'camila', texto:'Y yo te amo, Tich ❤️'}
  ],
  [
    {peluche:'tich', texto:'Camila, ¿y si Pinochito no es mi hijo? 😨'},
    {peluche:'camila', texto:'¡que locuras dices, Tich! 🤦‍♀️'},
    {peluche:'tich', texto:'Es que es demasiado bonito… yo no era así 😳'},
    {peluche:'camila', texto:'Pues eso lo saco de mi tontito 😏'},
    {peluche:'tich', texto:'¡Ah! Entonces no saco nada de mi 😤'},
    {peluche:'camila', texto:'Jajajaja, qué celos tan bobos 😂'},
    {peluche:'tich', texto:'Quiero ponerlo bajo investigación 🕵️'},
    {peluche:'camila', texto:'Y yo seré su abogada defensora ⚖️'},
    {peluche:'tich', texto:'¿Qué pruebas tienes? 🤔'},
    {peluche:'camila', texto:'Que se duerme igual que tú: roncando y que le gusta jugar video juegos tdoa la noche 😴'},
    {peluche:'tich', texto:'Ay no, ya me delataste 😅'},
    {peluche:'camila', texto:'Eso lo hace tu clon perfecto 👶'},
    {peluche:'tich', texto:'Entonces retiro la acusación 😌'},
    {peluche:'camila', texto:'Sabia decisión, señor juez 😎'},
    {peluche:'tich', texto:'Pero quiero beso como pago 😘'},
    {peluche:'camila', texto:'Con intereses 💕'},
    {peluche:'tich', texto:'Así me convences siempre 😍'},
    {peluche:'camila', texto:'Porque te amo, celosito 💖'},
    {peluche:'tich', texto:'Y yo a ti, abogadita del corazón ❤️'},
    {peluche:'camila', texto:'Nuestro mejor caso siempre será el amor 😍'}
  ],
  [
    {peluche:'Tich', texto:'Camila, anoche escuchaste a papi y mami? 😳'},
    {peluche:'Camila', texto:'Sí, parecía que estaban... jugando fuerte 🤭'},
    {peluche:'Tich', texto:'Yo pensé que era una pelea, pero luego se reían raro.'},
    {peluche:'Camila', texto:'Jajaja, seguro era un juego secreto solo para ellos.'},
    {peluche:'Tich', texto:'Entonces qué hacían?'},
    {peluche:'Camila', texto:'Un entrenamiento secreto, obvio.'},
    {peluche:'Tich', texto:'No me convence… sonaba muy intenso.'},
    {peluche:'Camila', texto:'Te pones rojo solo de recordarlo.'},
    {peluche:'Tich', texto:'Porque me da celos, Camila.'},
    {peluche:'Camila', texto:'Awww, mi osito celoso.'},
    {peluche:'Tich', texto:'Qué tal si papi le roba todos tus abrazos a mami?'},
    {peluche:'Camila', texto:'Entonces tú me das abrazos dobles.'},
    {peluche:'Tich', texto:'Trato hecho 💕'},
    {peluche:'Camila', texto:'Aunque sigo intrigada… qué será ese "más despacio" 🤔'},
    {peluche:'Tich', texto:'Yo digo que era yoga extremo.'},
    {peluche:'Camila', texto:'O un juego raro de cosquillas.'},
    {peluche:'Tich', texto:'Sea lo que sea, prometo que nunca te dejaré con dudas.'},
    {peluche:'Camila', texto:'Ni yo a ti, detective indiscreto 😘'}
  ],
  [
    {peluche:'tich', texto:'Camila, ese niño no se parece en nada a mí 😒'},
    {peluche:'camila', texto:'¡Otra vez con lo mismo, Tich! 🙄'},
    {peluche:'tich', texto:'Míralo bien, hasta parece hijo del vecino 👀'},
    {peluche:'camila', texto:'Jajajaja, no digas locuras 😂'},
    {peluche:'tich', texto:'Yo quiero una prueba de ADN 🧪'},
    {peluche:'camila', texto:'La única prueba es que heredó tu cabezota fea 😏'},
    {peluche:'tich', texto:'¿Feo yo? 😳'},
    {peluche:'camila', texto:'Feo y celoso, pero mío ❤️'},
    {peluche:'tich', texto:'Bueno, sí se ríe como yo… fuerte y raro 😂'},
    {peluche:'camila', texto:'¿Ves? Igualito a su papá 😍'},
    {peluche:'tich', texto:'Entonces sí puedo estar tranquilo 😌'},
    {peluche:'camila', texto:'Tranquilísimo, detective de celos 🕵️'},
    {peluche:'tich', texto:'Ok, retiro la demanda 😎'},
    {peluche:'camila', texto:'Caso cerrado ⚖️'},
    {peluche:'tich', texto:'Pero con beso de conciliación 😘'},
    {peluche:'camila', texto:'Aquí está mi firma 💋'},
    {peluche:'tich', texto:'Y aquí la mía 😍'},
    {peluche:'camila', texto:'Te amo, tontito celoso 💖'},
    {peluche:'tich', texto:'Y yo a ti, abogadita de mis dudas ❤️'},
    {peluche:'camila', texto:'Siempre juntos, juez y abogada del amor 😍'}
  ],
  [
    {peluche:'Tich', texto:'Camiii, papi y mami esconden algo bajo las cobijas 😳'},
    {peluche:'Camila', texto:'Jajaja, seguro es otro jueguito de ellos 🤭'},
    {peluche:'Tich', texto:'Yo vi que mami se tapaba hasta la cabeza 😱'},
    {peluche:'Camila', texto:'Eso es para que nadie los descubra 🙊'},
    {peluche:'Tich', texto:'Pero yo soy espía, nada se me escapa 🕵️‍♂️'},
    {peluche:'Camila', texto:'¿Y qué viste, detective? 👀'},
    {peluche:'Tich', texto:'Mucho movimiento sospechoso 😤'},
    {peluche:'Camila', texto:'Jajajaja, ay Dios mío, este osito… 😂'},
    {peluche:'Tich', texto:'Seguro papi estaba atrapado y pedía ayuda 🙄'},
    {peluche:'Camila', texto:'O seguro estaba feliz y tú con celos 😏'},
    {peluche:'Tich', texto:'Es que papi no debería divertirse tanto con mami 😔'},
    {peluche:'Camila', texto:'Tonto, es que se aman, igual que nosotros 💕'},
    {peluche:'Tich', texto:'Pues que jueguen de día, yo quiero dormir 😤'},
    {peluche:'Camila', texto:'O mejor jugamos nosotros y los dejamos tranquilos 😘'},
    {peluche:'Tich', texto:'¡Eso sí! Mi juego favorito eres tú 💞'},
    {peluche:'Camila', texto:'Entonces dame un abrazo fuertecito 💖'},
    {peluche:'Tich', texto:'Abrazo activado 🤗'},
    {peluche:'Camila', texto:'Y un besito para cerrar la misión 😘'},
    {peluche:'Tich', texto:'Misión cumplida, mi amor 💕'}
  ],
  [
    {peluche:'Tich', texto:'Camiii, creo que papi quiere quitarme a mami 😤'},
    {peluche:'Camila', texto:'Jajajaja, pero si ella es tu mami también 😂'},
    {peluche:'Tich', texto:'Sí, pero le hace cosquillas escondidas 🙄'},
    {peluche:'Camila', texto:'Eso se llama amor travieso 😏'},
    {peluche:'Tich', texto:'Pues que me haga cosquillas a mí también 😔'},
    {peluche:'Camila', texto:'Ay, celosito… tú tienes mi atención 💕'},
    {peluche:'Tich', texto:'Pero papi la hace gritar más que yo 😱'},
    {peluche:'Camila', texto:'Jajajaja, ay Dios, qué ocurrencias 😂'},
    {peluche:'Tich', texto:'Yo también quiero ser el motivo de tus gritos 😎'},
    {peluche:'Camila', texto:'Jajajaja, a ver grítame "te amo" fuertecito 🤭'},
    {peluche:'Tich', texto:'¡TE AMOOOO CAMIILITAAAAAAAAAAA DINDAAAAAAAAAA! 💖'},
    {peluche:'Camila', texto:'Jajajaja, así sí me gusta 😍'},
    {peluche:'Tich', texto:'Entonces ya no extraño nada de papi 😤'},
    {peluche:'Camila', texto:'Claro, porque conmigo tienes todo 💞'},
    {peluche:'Tich', texto:'Es que a veces me pongo celoso sin razón 😔'},
    {peluche:'Camila', texto:'Y yo te calmo con besitos 😘'},
    {peluche:'Tich', texto:'Dame uno ahora mismo 🙄'},
    {peluche:'Camila', texto:'Muack 💖'},
    {peluche:'Tich', texto:'Ya no hay celos, solo amor 🥰'}
  ],
  [
    {peluche:'tich', texto:'Camila… tengo que decirte algo muy serio 😒'},
    {peluche:'camila', texto:'¿Y ahora qué drama inventaste, Tich? 😂'},
    {peluche:'tich', texto:'¡Yo creo que… Pinochito no es hijo mío! 😱'},
    {peluche:'camila', texto:'¡¿Quéééé?! 🤦‍♀️ No digas bobadas.'},
    {peluche:'tich', texto:'¡Míralo bien! No se parece a mí 👀'},
    {peluche:'camila', texto:'Es un bebé peluche, todos son distintos 😅'},
    {peluche:'tich', texto:'¡Ajá! Seguro es porque estuviste con muchos hombres 😤'},
    {peluche:'camila', texto:'😳 ¡Oye, respetá! Yo no soy así.'},
    {peluche:'tich', texto:'Entonces explícalo… ¿por qué se llama Pinochito? 🤔'},
    {peluche:'camila', texto:'Porque es tierno y pequeñito, mami fue quien elijio ese nombre 🙄'},
    {peluche:'tich', texto:'¡Ajá, lo sabía! le dicen pinochito porque esta echo de muchos palos 😡'},
    {peluche:'camila', texto:'😂 Eres un celoso cabezon'},
    {peluche:'tich', texto:'No me da risa, Camila… esto me lastima 💔'},
    {peluche:'camila', texto:'Ay Tich, tontito… claro que es tu hijo 😍'},
    {peluche:'tich', texto:'¿De verdad? ¿No me engañaste? 😟'},
    {peluche:'camila', texto:'Claro que no, mi detective dramático ❤️'},
    {peluche:'tich', texto:'Entonces sí puedo decirle "hijo" con orgullo 🥹'},
    {peluche:'camila', texto:'¡Obvio! Es nuestra mezcla perfecta 💕'},
    {peluche:'tich', texto:'Está bien… pero igual le haré prueba de ADN peluchil 🤨'},
    {peluche:'camila', texto:'Haz lo que quieras, celoso… pero solo te amo a ti 😘'}
  ],
  [
    {peluche:'tich', texto:'¡Camilita! Tenemos un caso misterioso y mágico! 🕵️‍♂️✨'},
    {peluche:'camila', texto:'¿Qué ocurre, detective Tich? Cuénteme los hechos ⚖️'},
    {peluche:'tich', texto:'¡El juguete de Pinochito apareció en otro lugar sin que nadie lo tocara! 🧸😱'},
    {peluche:'camila', texto:'¡Imposible! Necesito pruebas claras ⚖️🔍'},
    {peluche:'tich', texto:'Lo vi con mis propios ojos, se movió solito 🕵️‍♂️'},
    {peluche:'camila', texto:'Mmm… la magia no es válida en el tribunal ⚖️🙅‍♀️'},
    {peluche:'tich', texto:'¡Pero Camilita, no hay explicación lógica! 🕵️‍♂️'},
    {peluche:'camila', texto:'Debe haber una… ¡todo tiene una razón! ⚖️🤔'},
    {peluche:'tich', texto:'¡Esperaaaaa! Encontré huellas pequeñitas 🕵️‍♂️👣'},
    {peluche:'camila', texto:'¿Huellas? 😲 A ver, preséntelas como evidencia ⚖️📑'},
    {peluche:'tich', texto:'¡Son de Pinochito! Él mismo movió su juguete medio dormido 😴🧸'},
    {peluche:'camila', texto:'¡Ajá! Entonces el acusado es… ¡Pinochito! ⚖️😆'},
    {peluche:'tich', texto:'Jajajaja, sí, nos engañó como a principiantes 🕵️‍♂️😂'},
    {peluche:'camila', texto:'¡Caso cerrado! Pinochito es travieso pero inocente ⚖️💕'},
    {peluche:'tich', texto:'Y muy astuto, igualito a su mami 😏💖'},
    {peluche:'camila', texto:'Y también a su papi detective 😌🕵️‍♂️'},
    {peluche:'tich', texto:'Somos el mejor equipo: detective y abogada 🕵️‍♂️⚖️✨'},
    {peluche:'camila', texto:'¡Con el mejor ayudante travieso del mundo! 🧸'},
    {peluche:'tich', texto:'Sí, Pinochito, nuestro pequeño cómplice 🥰'},
    {peluche:'camila', texto:'¡Familia unida, caso resuelto! 💖⚖️🕵️‍♂️'}
  ],
  [
    {peluche:'Tich', texto:'Camila, escuchaste a mami anoche? 😳'},
    {peluche:'Camila', texto:'Sí, parecía que estaba cantando ópera 😂'},
    {peluche:'Tich', texto:'Y papi la acompañaba con un "más, más" 🎶'},
    {peluche:'Camila', texto:'Eso no fue un concierto… fue otra cosa 🙊'},
    {peluche:'Tich', texto:'Seguro papi le estaba haciendo cosquillas 🤭'},
    {peluche:'Camila', texto:'O tal vez estaban ensayando un nuevo baile 💃🕺'},
    {peluche:'Tich', texto:'Yo sentí que la cama hasta temblaba 😱'},
    {peluche:'Camila', texto:'Jajajaja, entonces era un "baile fuertecito" 😂'},
    {peluche:'Tich', texto:'No sé, pero yo me puse celoso 😒'},
    {peluche:'Camila', texto:'¿Celoso de qué, tontico? 🙄'},
    {peluche:'Tich', texto:'De que papi hace reír a mami más que yo 😤'},
    {peluche:'Camila', texto:'Ay, pero a mí también me haces reír cada día 💕'},
    {peluche:'Tich', texto:'Eso sí, yo quiero ser tu único cantante 😎'},
    {peluche:'Camila', texto:'Jajaja, entonces cántame ahora mismito 🎶'},
    {peluche:'Tich', texto:'♪ Camiii, no me dejes nunca ♪ 😍'},
    {peluche:'Camila', texto:'Jajajaja, qué romántico mi osito 🎤'},
    {peluche:'Tich', texto:'A que papi no te canta así 🙄'},
    {peluche:'Camila', texto:'Pues no, papi tiene otros "conciertos secretos" 🤫'},
    {peluche:'Tich', texto:'Entonces yo soy tu cantante oficial 💞'},
    {peluche:'Camila', texto:'Y tuya seré, para siempre 💖'}
  ],
  [
    {peluche:'Tich', texto:'Detective Tich en acción 🕵️‍♂️. Algo raro pasa con papi y mami…'},
    {peluche:'Camila', texto:'¿Qué encontraste ahora, detective celoso? 🙄'},
    {peluche:'Tich', texto:'Huelo a sudor sospechoso en las cobijas 😳'},
    {peluche:'Camila', texto:'Jajajaja, qué exagerado 😂'},
    {peluche:'Tich', texto:'Además, mami salió despeinada esta mañana 🤔'},
    {peluche:'Camila', texto:'Tal vez estaban luchando con las almohadas 😏'},
    {peluche:'Tich', texto:'¡Exacto! Una batalla nocturna 😱'},
    {peluche:'Camila', texto:'O un entrenamiento secreto de pareja 💪'},
    {peluche:'Tich', texto:'Pero papi estaba sin camiseta… muy raro 😤'},
    {peluche:'Camila', texto:'Jajajaja, eso no es prueba suficiente, detective 😅'},
    {peluche:'Tich', texto:'Y mami decía: "¡basta ya!" 🤯'},
    {peluche:'Camila', texto:'Jajaja, seguro perdió la pelea de cosquillas 🤭'},
    {peluche:'Tich', texto:'No me convence, Camiii 😒'},
    {peluche:'Camila', texto:'Entonces sigamos investigando 😏'},
    {peluche:'Tich', texto:'Pero me da celitos… ¿y si se quieren más que a nosotros? 😔'},
    {peluche:'Camila', texto:'Ay tontico, el amor de ellos es distinto 💕'},
    {peluche:'Tich', texto:'¿Seguro? 😳'},
    {peluche:'Camila', texto:'Claro, porque tú eres el único dueño de mi corazón 💖'},
    {peluche:'Tich', texto:'Entonces cierro el caso: Camila me ama a mí 😎'},
    {peluche:'Camila', texto:'Caso cerrado, detective celosito 💞'}
  ],
  [
    {peluche:'tich', texto:'¡Camilita! ¡Eres una mentirosa! 😡'},
    {peluche:'camila', texto:'¿Qué? ¿Por qué me dices eso, Tich? 😤'},
    {peluche:'tich', texto:'¡Porque dijiste que ibas a guardarme la última galleta y te la comiste! 🍪😡'},
    {peluche:'camila', texto:'¡Ay, pero tenía mucha hambre! 😳 No fue mentira…'},
    {peluche:'tich', texto:'¡Sí fue mentira! Dijiste que era para mí 😭'},
    {peluche:'camila', texto:'Bueno… pero es que estaba tan rica 😅'},
    {peluche:'tich', texto:'¡Entonces eres tramposa y mentirosa! 😡'},
    {peluche:'camila', texto:'¡Y tú eres un celoso exagerado! 😤'},
    {peluche:'tich', texto:'¡No soy celoso! Solo quería mi galleta 😭'},
    {peluche:'camila', texto:'Jajaja, ay Tichito, estás todo bravo pero te ves lindo 😏💕'},
    {peluche:'tich', texto:'¡No me digas lindo, estoy bravo! 😡'},
    {peluche:'camila', texto:'Pues yo sí te quiero aunque estés bravo 😌💖'},
    {peluche:'tich', texto:'Mmm… ¿de verdad? 🥺'},
    {peluche:'camila', texto:'Claro que sí, tontito. Eres mi Tichito y siempre te voy a querer 💕'},
    {peluche:'tich', texto:'Bueno… te perdono, pero la próxima vez compartes la galleta conmigo 😏'},
    {peluche:'camila', texto:'Hecho 🤝 mitad para ti y mitad para mí 😋'},
    {peluche:'tich', texto:'Está bien… aunque yo quiero la parte más grande 😏🍪'},
    {peluche:'camila', texto:'¡Jajajaja, abusivo! Pero igual te la doy 💖'},
    {peluche:'tich', texto:'Ay Camilita… no puedo estar bravo contigo 🥰'},
    {peluche:'camila', texto:'Yo tampoco contigo, mi Tichito lindo 💕'}
  ],
  [
    {peluche:'Tich', texto:'Camiii, anoche escuché ruidos raros en el cuarto de papi y mami 😳'},
    {peluche:'Camila', texto:'¿Qué tipo de ruidos, Tich? 👀'},
    {peluche:'Tich', texto:'Como si estuvieran peleando… pero entre risitas 🙄'},
    {peluche:'Camila', texto:'Eso no suena a pelea, suena a jueguito secreto 😏'},
    {peluche:'Tich', texto:'¡Ajá! ¿Y por qué no nos invitan a jugar también? 😤'},
    {peluche:'Camila', texto:'Porque es un juego solo de grandes, tontito 🤭'},
    {peluche:'Tich', texto:'Seguro papi estaba perdiendo y mami se le subió encima 🤔'},
    {peluche:'Camila', texto:'Jajajaja, qué imaginación tienes 😂'},
    {peluche:'Tich', texto:'Pues yo oí a papi decir: "¡ya no aguanto más!" 😱'},
    {peluche:'Camila', texto:'Jajajaja, eso sí parece sospechoso 🤐'},
    {peluche:'Tich', texto:'Yo creo que estaban luchando bajo las cobijas 🥷'},
    {peluche:'Camila', texto:'Sí, pero era más como una lucha con besitos 😘'},
    {peluche:'Tich', texto:'¡Camiii! No me digas esas cosas, que me pongo celoso 😒'},
    {peluche:'Camila', texto:'Ay, tontico, ellos también se quieren, igual que tú y yo 💕'},
    {peluche:'Tich', texto:'Pues que jueguen más bajito, que yo no dormí nada 😤'},
    {peluche:'Camila', texto:'Jajaja, o será que estabas espiando todo 👀'},
    {peluche:'Tich', texto:'Bueno… un poquito, quería descubrir el secreto 😳'},
    {peluche:'Camila', texto:'Y al final, ¿qué descubriste detective? 🕵️‍♂️'},
    {peluche:'Tich', texto:'Que papi y mami esconden el juego más divertido del mundo 😏'},
    {peluche:'Camila', texto:'Y nosotros lo llamamos… "amor travieso" 💞'}
  ],
  [
    {peluche:'tich', texto:'Camila, Pinochito no me mira como debería 😒'},
    {peluche:'camila', texto:'¿Y cómo debería mirarte? 🤔'},
    {peluche:'tich', texto:'Con respeto, soy su papá 😤'},
    {peluche:'camila', texto:'Jajajaja, apenas es un bebé 😂'},
    {peluche:'tich', texto:'Pues parece que te prefiere a ti 😢'},
    {peluche:'camila', texto:'Porque yo le doy la comida 😌'},
    {peluche:'tich', texto:'Ah, con razón… entonces yo soy el divertido 😎'},
    {peluche:'camila', texto:'Exacto, el de los juegos 🥳'},
    {peluche:'tich', texto:'Pero igual me da celos 😒'},
    {peluche:'camila', texto:'No seas bobo, te adora ❤️'},
    {peluche:'tich', texto:'¿Seguro? 🤨'},
    {peluche:'camila', texto:'Segurísimo, eres su héroe 🦸‍♂️'},
    {peluche:'tich', texto:'Ok, retiro mi queja 😌'},
    {peluche:'camila', texto:'Caso archivado 📂'},
    {peluche:'tich', texto:'Pero quiero recompensa 😘'},
    {peluche:'camila', texto:'Aquí tienes un beso gigante 💕'},
    {peluche:'tich', texto:'Ya no siento celos 😍'},
    {peluche:'camila', texto:'Viste, tontito lindo 😏'},
    {peluche:'tich', texto:'Te amo, Camila 💖'},
    {peluche:'camila', texto:'Y yo te amo más, Tich ❤️'}
  ],
  [
    {peluche:'Tich', texto:'¿Te acuerdas cuando papi nos puso en la cama?'},
    {peluche:'Camila', texto:'¡Siii! Y luego nos hizo volar como si fuéramos aviones ✈️'},
    {peluche:'Tich', texto:'Yo casi me estrello contra la mesa, mami gritó "¡cuidadooo!" 😂'},
    {peluche:'Camila', texto:'Jajaja y papi solo dijo "tranquila, tengo práctica"'},
    {peluche:'Tich', texto:'Al final me dio un aterrizaje forzoso en su barriga jeje'},
    {peluche:'Camila', texto:'Yo fui copilota, él me hacía girar y decía "Camila comandante"'},
    {peluche:'Tich', texto:'Y Pinochito se quedó mirando celoso desde la cama 🤭'},
    {peluche:'Camila', texto:'¡Claro! Hasta hizo puchero porque no lo subieron al avión'},
    {peluche:'Tich', texto:'Ese papi juega duro, pero nos abraza fuerte al final'},
    {peluche:'Camila', texto:'Y mami diciendo: "parecen niños chiquitos los tres" jaja'},
    {peluche:'Tich', texto:'Yo después me quedé dormido en la barriga de papi 💤'},
    {peluche:'Camila', texto:'Yo en su brazo, aunque se me dormía la cabecita'},
    {peluche:'Tich', texto:'Esos juegos me gustan, aunque a veces casi me da vértigo'},
    {peluche:'Camila', texto:'Pues a mí me encantó ser avioncito, papi me hacía reír mucho'},
    {peluche:'Tich', texto:'Pero el avión más bonito eras tú, siempre sonreías 🥰'},
    {peluche:'Camila', texto:'Ay Tich, me derrites, hasta en los recuerdos te pones romántico'},
    {peluche:'Tich', texto:'Porque contigo todo se vuelve especial 💕'},
    {peluche:'Camila', texto:'Con papi y mami siempre tenemos aventuras raras jeje'},
    {peluche:'Tich', texto:'Y yo siempre quiero que sean así, llenas de risa y amor'},
    {peluche:'Camila', texto:'Entonces prometo más vuelos contigo y nuestra familia ✨'}
  ],
  [
    {peluche:'Camila', texto:'¿Te acuerdas cuando mami nos sacó al patio?'},
    {peluche:'Tich', texto:'¡Sí! Nos puso sobre la hamaca y nos meció despacito 🌙'},
    {peluche:'Camila', texto:'Y cantaba esa canción que tanto le gusta mientras barría'},
    {peluche:'Tich', texto:'Yo pensé que me iba a marear con tanto movimiento jeje'},
    {peluche:'Camila', texto:'Yo en cambio casi me dormía con su vocecita tan suave'},
    {peluche:'Tich', texto:'Después nos dejó tomar solecito un ratito ☀️'},
    {peluche:'Camila', texto:'Ahí fue cuando Pinochito dijo que quería ser girasol 🌻'},
    {peluche:'Tich', texto:'Jajaja sí, porque se inclinaba hacia la luz'},
    {peluche:'Camila', texto:'Mami le dijo: "eres mi florecita consentida"'},
    {peluche:'Tich', texto:'Yo puse cara de celoso, ¿recuerdas?'},
    {peluche:'Camila', texto:'Y yo te dije: "para mí tú eres mi árbol fuerte"'},
    {peluche:'Tich', texto:'Ese día jugamos a las escondidas entre las sábanas tendidas'},
    {peluche:'Camila', texto:'Y mami nos encontró diciendo: "¡ahí están mis chiquitos!"'},
    {peluche:'Tich', texto:'Luego nos puso a todos junticos en la hamaca otra vez'},
    {peluche:'Camila', texto:'Y nos dio besitos en la frente, como siempre hace 💖'},
    {peluche:'Tich', texto:'Yo sentí que éramos como parte del patio mismo'},
    {peluche:'Camila', texto:'Es que con mami todo se siente natural y bonito'},
    {peluche:'Tich', texto:'Sí, como un paseo sin salir de casa'},
    {peluche:'Camila', texto:'Y con su amor, cualquier lugar es el mejor lugar 🥰'}
  ],
  [
    {peluche:'tich', texto:'Camila, creo que Pinochito heredó tu lado travieso 😏'},
    {peluche:'camila', texto:'¿Y por qué lo dices? 🤔'},
    {peluche:'tich', texto:'Porque rompe todo… ¡igual que tú mis planes! 😂'},
    {peluche:'camila', texto:'Jajajaja, y tú celoso igual que siempre 🙄'},
    {peluche:'tich', texto:'No quiero que me lo quites, es mío 😤'},
    {peluche:'camila', texto:'¡Nuestro! 😍'},
    {peluche:'tich', texto:'Bueno, pero se parece más a ti… 😒'},
    {peluche:'camila', texto:'Eso es bueno, porque me amas 😘'},
    {peluche:'tich', texto:'Ay, no sé si reír o llorar 😅'},
    {peluche:'camila', texto:'Mejor ríe conmigo 💕'},
    {peluche:'tich', texto:'Está bien, pero solo si me das pruebas 😏'},
    {peluche:'camila', texto:'La prueba es que dice "papá" primero 👶'},
    {peluche:'tich', texto:'¿De verdad? 😳'},
    {peluche:'camila', texto:'De verdad, tontito lindo ❤️'},
    {peluche:'tich', texto:'Entonces soy el papá oficial 😎'},
    {peluche:'camila', texto:'El único, detective de mi corazón 🕵️'},
    {peluche:'tich', texto:'Te amo por aclarar mis celos 💖'},
    {peluche:'camila', texto:'Y yo te amo aunque inventes teorías raras 😂'},
    {peluche:'tich', texto:'Somos la mejor pareja de locos 😍'},
    {peluche:'camila', texto:'Locos de amor eterno ❤️'}
  ],
  [
    {peluche:'tich', texto:'Camilita, ¿te acuerdas cuando papi nos perfumó toda la casa aquella vez?'},
    {peluche:'camila', texto:'¡Sí! Me dejó oliendo a su colonia por días, casi me vuelvo un frasquito 🤭'},
    {peluche:'tich', texto:'Él decía que así, cuando mami nos abrazara, la recordaría y sonreiría 💭'},
    {peluche:'camila', texto:'Me daba risa porque me sentía gigante y elegante al mismo tiempo 😅'},
    {peluche:'tich', texto:'Papi me echó un poquito en la pancita y yo quedé oliendo a aventuras 🚀'},
    {peluche:'camila', texto:'A mí me puso en la cabecita y decía: "para que mi niña lleve mi olor" 🥹'},
    {peluche:'tich', texto:'Cuando llegamos con mami, ella nos apretó y soltó una sonrisa enorme 😍'},
    {peluche:'camila', texto:'Se quedó oliendo mi orejita como si guardara el recuerdo en su pecho 💖'},
    {peluche:'tich', texto:'Me dio ternura ver cómo un perfume podía traer tanta calma y alegría ✨'},
    {peluche:'camila', texto:'Y papi se quedó orgulloso, diciendo que era su pequeño truco de amor 😊'},
    {peluche:'tich', texto:'Hasta Pinochito parecía notar el olor y se calmó enseguida 🍼'},
    {peluche:'camila', texto:'Me acuerdo que mami nos dijo: "huelen a casa" y se le llenaron los ojos 💕'},
    {peluche:'tich', texto:'Yo sentí que éramos un pedacito de ellos, con olor a papá y calor de hogar 🏠'},
    {peluche:'camila', texto:'Después, cada vez que olía esa colonia pensaba en papi y en la tarde en el pueblo 🌇'},
    {peluche:'tich', texto:'Papi lo hizo con cariño, como cuando arregla la sábana o cuenta un cuento 📚'},
    {peluche:'camila', texto:'Y aunque a veces me parecía fuerte, me gustaba porque sabía a su abrazo 🤗'},
    {peluche:'tich', texto:'Prometimos que cuando papi vuelva nos vamos a quedar oliendo a él, como premio 💝'},
    {peluche:'camila', texto:'Sí, para que mami siempre lo sienta cerca aunque estén lejos ✨'},
    {peluche:'tich', texto:'Pequeños trucos que hacen grande la familia, ¿no crees?'},
    {peluche:'camila', texto:'Totalmente. Esas son las cosas que guardo en el corazón, mi cabezón 💕'}
  ],
  [
    {peluche:'Tich', texto:'¿Te acuerdas del día que Johan y José Migue me rompieron un poquito? 😢'},  
    {peluche:'Camila', texto:'Sí, amor… estabas todo triste y asustado.'},  
    {peluche:'Tich', texto:'Sentí que ya no iba a estar igual, como si me fueran a olvidar.'},  
    {peluche:'Camila', texto:'Pero mami te abrazó, te cosió con tanto cuidado y quedaste más fuerte 💖.'},  
    {peluche:'Tich', texto:'Eso sí, me dolió… aunque lo que más me dolió fue que tú lloraste conmigo.'},  
    {peluche:'Camila', texto:'¿Y cómo no iba a llorar? ¡Eres mi hermanito enamorado!'},  
    {peluche:'Tich', texto:'Después te tocó a ti, cuando casi te rompieron el cuello 😔.'},  
    {peluche:'Camila', texto:'Ay sí, ese día pensé que ya no podría girar la cabeza.'},  
    {peluche:'Tich', texto:'Yo quería protegerte, pero era muy pequeñito para pelear con ellos.'},  
    {peluche:'Camila', texto:'Tranquilo, lo importante es que mami me cuidó, me cosió y me dejó como nueva ✨.'},  
    {peluche:'Tich', texto:'Mami es como nuestra doctora secreta 🧵❤️.'},  
    {peluche:'Camila', texto:'Sí, y hasta nos curó con besitos para que no quedara la herida.'},  
    {peluche:'Tich', texto:'Creo que por eso todavía olemos a su perfume.'},  
    {peluche:'Camila', texto:'Y por eso sentimos que nada nos puede separar.'},  
    {peluche:'Tich', texto:'Aunque a veces los juegos de Johan y José Migue eran muy bruscos.'},  
    {peluche:'Camila', texto:'Jajaja sí, parecían luchadores profesionales 😂.'},  
    {peluche:'Tich', texto:'Pero gracias a eso, ahora tenemos cicatrices que son como medallas.'},  
    {peluche:'Camila', texto:'Medallas de amor, porque nos recuerdan que mami siempre está para salvarnos.'},  
    {peluche:'Tich', texto:'Y yo siempre estaré para cuidarte, aunque me rompa mil veces 💕.'},  
    {peluche:'Camila', texto:'Y yo para abrazarte, hasta que se nos acaben las costuras y más.'}
  ],
  [
    {peluche:'tich', texto:'¡Camilita! ¿Por qué le das más atención a pinochito? 😡'},
    {peluche:'camila', texto:'¿Qué? ¿Por qué me gritas? 😤'},
    {peluche:'tich', texto:'¡Porque me ignoras! 😡'},
    {peluche:'camila', texto:'¡No te ignoro! ¡Pinochito es un bebé! 😡'},
    {peluche:'tich', texto:'¡NO! ¡A MÍ ME IGNORAS! 😡'},
    {peluche:'camila', texto:'¡NO! ¡TÚ ERES CELOSO! 😡'},
    {peluche:'tich', texto:'¡NO! ¡TÚ ERES UNA MALA NOVIA! 😡'},
    {peluche:'camila', texto:'¡NO! ¡TÚ ERES UN MAL NOVIO! 😡'},
    {peluche:'tich', texto:'¡CALLATE! ¡MALCRIADA! 😡'},
    {peluche:'camila', texto:'¡NO! ¡TÚ CALLATE! ¡MALCRIADO! 😡'},
    {peluche:'tich', texto:'¡ERES UNA EGOÍSTA! 😡'},
    {peluche:'camila', texto:'¡NO! ¡TÚ ERES EGOÍSTA! 😡'},
    {peluche:'tich', texto:'¡CALLATE! ¡CALLATE! 😡'},
    {peluche:'camila', texto:'¡NO! ¡TÚ CALLATE! 😡'},
    {peluche:'tich', texto:'¡NO TE QUIERO! 😡'},
    {peluche:'camila', texto:'¡NO! ¡YO NO TE QUIERO! 😡'},
    {peluche:'tich', texto:'¡CALLATE! ¡CALLATE! 😡'},
    {peluche:'camila', texto:'¡NO! ¡NO! ¡NO! 😡'},
    {peluche:'tich', texto:'¡CALLATE! ¡CALLATE! 😡'},
    {peluche:'camila', texto:'¡NO! ¡NO! ¡NO! 😡'}
  ],

  // CONVERSACIONES DE CONVERSACIONES.JS
  [
    {peluche:'tich', texto:'Camilita, ¿por qué estabas tanto con papi hoy? 😤'},
    {peluche:'camila', texto:'¡Porque me estaba contando algo de la universidad! 🙄'},
    {peluche:'tich', texto:'Seguro le sonreíste como me sonríes a mí 😒'},
    {peluche:'camila', texto:'¡No seas bobo, Tich! A papi lo quiero, pero no como a ti 😠'},
    {peluche:'tich', texto:'Pues yo siento que sí… y no me gusta nada 😢'},
    {peluche:'camila', texto:'Ay mi amor, eres mi único corazoncito 💖'},
    {peluche:'tich', texto:'Pero me da miedo perderte 😔'},
    {peluche:'camila', texto:'Nunca vas a perderme, Tichito 🤗'},
    {peluche:'tich', texto:'¿Lo juras por nuestras estrellitas? ⭐'},
    {peluche:'camila', texto:'Lo juro por todas las estrellas del cielo ✨'},
    {peluche:'tich', texto:'Entonces… ¿me das un besito de prueba? 😏'},
    {peluche:'camila', texto:'Jajajaja, sí, pero solo si dejas los celos 😘'},
    {peluche:'tich', texto:'Trato hecho 🤭'},
    {peluche:'camila', texto:'Eres mi niño celoso pero tierno 💕'},
    {peluche:'tich', texto:'Y tú mi niña perfecta 🌸'},
    {peluche:'camila', texto:'Ya no más peleas, ¿sí? 😌'},
    {peluche:'tich', texto:'Está bien, pero solo porque te amo mucho 💖'},
    {peluche:'camila', texto:'Y yo a ti, tontito mío 🤗'},
  ],
  [
    {peluche:'camila', texto:'Tich, ¿por qué estabas abrazado a mami tanto rato? 😤'},
    {peluche:'tich', texto:'Porque mami me estaba consintiendo, ¿y qué? 🙄'},
    {peluche:'camila', texto:'¡Pues que eres mío, no de ella! 😡'},
    {peluche:'tich', texto:'¡Mami me quiere mucho y yo también a ella! 😠'},
    {peluche:'camila', texto:'¡Pero yo soy tu Camila, tu amorcito! 😢'},
    {peluche:'tich', texto:'Ay… no llores, no quiero verte triste 😔'},
    {peluche:'camila', texto:'Es que siento que me cambias por mami 😣'},
    {peluche:'tich', texto:'Jamás te cambiaría, tú eres mi todo 💕'},
    {peluche:'camila', texto:'¿Entonces me prometes que soy la número uno? 😟'},
    {peluche:'tich', texto:'Sí, siempre serás la primera en mi corazón 💖'},
    {peluche:'camila', texto:'Y yo prometo no enojarme tanto 🤭'},
    {peluche:'tich', texto:'Me gusta más tu sonrisa que tus enojos 😅'},
    {peluche:'camila', texto:'Jajaja, lo sé, tontito 🤗'},
    {peluche:'tich', texto:'Perdón por hacerte llorar 😔'},
    {peluche:'camila', texto:'Y yo por gritarte… te amo 💕'},
    {peluche:'tich', texto:'Yo te amo más, Camilita 💖'},
    {peluche:'camila', texto:'Siempre juntos, aunque mami nos consienta 🤭'},
  ],
  [
    {peluche:'tich', texto:'Camilita, ¿mami está bien hoy? 😊'},
    {peluche:'camila', texto:'Sí, pero se ve un poquito cansada 😔'},
    {peluche:'tich', texto:'¿Crees que trabajó mucho? 💼'},
    {peluche:'camila', texto:'Sí, mami trabaja mucho para cuidarnos 💕'},
    {peluche:'tich', texto:'Mami es muy buena con nosotros 🥰'},
    {peluche:'camila', texto:'Sí, nos da mucho amor y cariño 💖'},
    {peluche:'tich', texto:'¿Le decimos que la amamos? 😊'},
    {peluche:'camila', texto:'¡Sí! Y que la extrañamos cuando no está 💕'},
    {peluche:'tich', texto:'Mami es la mejor mamá del mundo 🌟'},
    {peluche:'camila', texto:'¡Sí! Y papi es el mejor papá 💖'},
    {peluche:'tich', texto:'Tenemos los mejores papás del universo 🌌'},
    {peluche:'camila', texto:'¡Sí! Somos muy afortunados 😊'},
    {peluche:'tich', texto:'¿Le damos un abrazo a mami cuando venga? 🤗'},
    {peluche:'camila', texto:'¡Sí! Y muchos besitos 😘'},
    {peluche:'tich', texto:'Mami se va a poner muy feliz 😄'},
    {peluche:'camila', texto:'¡Sí! Y nosotros también 💕'},
    {peluche:'tich', texto:'Mami nos ama mucho 💖'},
    {peluche:'camila', texto:'Y nosotros la amamos más 💕'},
    {peluche:'tich', texto:'¡Mami es nuestra heroína! 🦸‍♀️'},
    {peluche:'camila', texto:'¡Sí! ¡La mejor heroína del mundo! 🌟'}
  ],
  [
    {peluche:'tich', texto:'Camilita, ¡hiciste trampa en el juego! 😠'},
    {peluche:'camila', texto:'¡No hice trampa, gané porque soy mejor! 😤'},
    {peluche:'tich', texto:'¡Mentira, hiciste trampa clarita! 😡'},
    {peluche:'camila', texto:'¡Ay Tich, siempre que pierdes inventas excusas! 🙄'},
    {peluche:'tich', texto:'¡No es excusa, yo vi cómo te adelantaste! 😤'},
    {peluche:'camila', texto:'Pues sí, me adelanté poquito… pero igual te iba a ganar 😏'},
    {peluche:'tich', texto:'¡Ajá! Lo aceptaste 😒'},
    {peluche:'camila', texto:'Jajaja, pero no te enojes, era un juego 🤭'},
    {peluche:'tich', texto:'Pues ya no quiero jugar 😔'},
    {peluche:'camila', texto:'Ay no, no te pongas triste 💕'},
    {peluche:'tich', texto:'Es que odio perder contigo 😣'},
    {peluche:'camila', texto:'Pero me amas aunque te gane, ¿cierto? 😏'},
    {peluche:'tich', texto:'Sí… y mucho 💖'},
    {peluche:'camila', texto:'Entonces ya no hay pelea 😘'},
    {peluche:'tich', texto:'Solo si me das revancha 😅'},
    {peluche:'camila', texto:'Hecho, pero sin berrinche 🤭'},
    {peluche:'tich', texto:'Prometido… aunque voy a ganar esta vez 🤗'},
    {peluche:'camila', texto:'Jajaja, eso quiero ver 💕'},
  ],
  [
    {peluche:'camila', texto:'Tich, ¿qué estabas escondiendo debajo de la cama? 🤨'},
    {peluche:'tich', texto:'¡Nada! No era nada importante 🙄'},
    {peluche:'camila', texto:'¡Sí era algo! Te vi guardándolo rápido 😠'},
    {peluche:'tich', texto:'Bueno… era un dibujito que hice para ti 😳'},
    {peluche:'camila', texto:'¿Y por qué no me lo mostrabas? 😤'},
    {peluche:'tich', texto:'Porque quería que fuera sorpresa, pero te pusiste curiosa 😒'},
    {peluche:'camila', texto:'Ay, es que no me gusta que me ocultes cosas 😢'},
    {peluche:'tich', texto:'No te oculto nada malo, tontita 💕'},
    {peluche:'camila', texto:'¿De verdad? 😟'},
    {peluche:'tich', texto:'De verdad, era un regalito secreto 🤫'},
    {peluche:'camila', texto:'Entonces perdón por enojarme 😔'},
    {peluche:'tich', texto:'Y yo por gritarte… no quería hacerlo 😞'},
    {peluche:'camila', texto:'¿Puedo ver el dibujo ahora? 🥺'},
    {peluche:'tich', texto:'Claro, pero prométeme no espiar la próxima 😅'},
    {peluche:'camila', texto:'Lo prometo 🤭'},
    {peluche:'tich', texto:'Eres mi curiosa preferida 💕'},
    {peluche:'camila', texto:'Y tú mi artista favorito 😍'},
    {peluche:'tich', texto:'Entonces estamos bien otra vez 🤗'},
    {peluche:'camila', texto:'Sí, siempre bien contigo 💖'},
  ],

  // CONVERSACIONES DE MAS_CONVERSACIONES.JS
  [
    {peluche:'tich', texto:'Abogada Camila, tenemos un caso urgente 🕵️‍♂️'},
    {peluche:'camila', texto:'¿Qué pasó ahora, detective Tich? ⚖️'},
    {peluche:'tich', texto:'Alguien se comió la última galleta de la cocina 🍪'},
    {peluche:'camila', texto:'¡Grave delito! Hay que encontrar al culpable 😱'},
    {peluche:'tich', texto:'Ya investigué y encontré migas en tu vestido 😏'},
    {peluche:'camila', texto:'Objeción, detective, esas migas pudieron ser plantadas 🙄'},
    {peluche:'tich', texto:'Entonces… ¿cómo explicas el olor a chocolate en tus manos? 😏'},
    {peluche:'camila', texto:'Ejem… podría ser de otra galleta 🤭'},
    {peluche:'tich', texto:'Ajá, confiesa de una vez 😤'},
    {peluche:'camila', texto:'Está bien… ¡me comí la galleta! 😅'},
    {peluche:'tich', texto:'Caso resuelto, la culpable era la abogada 😎'},
    {peluche:'camila', texto:'Pero espere detective… yo lo hice para compartirla contigo 💕'},
    {peluche:'tich', texto:'Ay, qué linda… eso cambia el veredicto 😍'},
    {peluche:'camila', texto:'Entonces, ¿soy inocente? 😳'},
    {peluche:'tich', texto:'Inocente y adorable 🤗'},
    {peluche:'camila', texto:'Jajajaja, me salvaste del castigo 😅'},
    {peluche:'tich', texto:'Y yo gané un besito de recompensa 😘'},
    {peluche:'camila', texto:'Tramposo, siempre sacas ventaja 🤭'},
    {peluche:'tich', texto:'Detective listo para otro caso 😏'},
    {peluche:'camila', texto:'Y abogada lista para defender lo indefendible 💖'},
  ],
  [
    {peluche:'camila', texto:'Detective Tich, tenemos una emergencia 😱'},
    {peluche:'tich', texto:'Dígame, abogada Camila, ¿cuál es el problema? 🕵️‍♂️'},
    {peluche:'camila', texto:'¡Pinochito desapareció de su cunita! 🍼'},
    {peluche:'tich', texto:'Tranquila, voy a investigar las pistas 🔍'},
    {peluche:'camila', texto:'Yo prepararé la defensa por si acusan a alguien inocente ⚖️'},
    {peluche:'tich', texto:'Mira, encontré huellitas pequeñas hacia la sala 👣'},
    {peluche:'camila', texto:'Eso significa que alguien lo cargó hasta allá 😳'},
    {peluche:'tich', texto:'Ajá, y en la sala hay un osito sospechoso 🧸'},
    {peluche:'camila', texto:'Objeción, detective, no hay pruebas suficientes 🙄'},
    {peluche:'tich', texto:'¡Pero lo encontré abrazando a Pinochito! 😏'},
    {peluche:'camila', texto:'Entonces el osito es culpable de secuestro de ternura 🤭'},
    {peluche:'tich', texto:'Jajaja, caso cerrado 😅'},
    {peluche:'camila', texto:'Qué bueno, ya estaba preocupada 💕'},
    {peluche:'tich', texto:'Nuestro bebé está a salvo, gracias a nosotros 😍'},
    {peluche:'camila', texto:'Equipo perfecto: tú investigas y yo defiendo 🤗'},
    {peluche:'tich', texto:'Juntos resolvemos cualquier misterio 💖'},
    {peluche:'camila', texto:'Y nadie puede vencernos 😏'},
    {peluche:'tich', texto:'Ni siquiera los papis sospechan de nuestras aventuras 🤫'},
    {peluche:'camila', texto:'Shhh, que siga siendo nuestro secreto 😌'},
  ],
  [
    {peluche:'camila', texto:'Tichito, yo extraño muchísimo a mami 😢'},
    {peluche:'tich', texto:'Lo sé, Camilita… pero yo estoy con ella y te manda muchos besitos 💕'},
    {peluche:'camila', texto:'Ay, eso me alegra, dale un abrazo muy fuerte de mi parte 🤗'},
    {peluche:'tich', texto:'Claro que sí, siempre hablo de ti y ella sonríe 🌸'},
    {peluche:'camila', texto:'Es que mami es la mejor, siempre tan fuerte y amorosa 🥹'},
    {peluche:'tich', texto:'Sí, yo la veo luchar cada día y me siento muy orgulloso ✨'},
    {peluche:'camila', texto:'Yo también, aunque la tenga lejos, siempre la llevo en mi corazón 💖'},
    {peluche:'tich', texto:'Y también extrañas a papi, ¿cierto? 😳'},
    {peluche:'camila', texto:'Muchísimo… a veces me da nostalgia no tenerlo aquí 🥺'},
    {peluche:'tich', texto:'Papi está estudiando duro en Sincelejo, y eso es para nuestro futuro 📚'},
    {peluche:'camila', texto:'Sí, y por eso estoy tan orgullosa de él 💪'},
    {peluche:'tich', texto:'Cuando lo veo llegar cansado, pienso: "qué grande es mi papi" 🌟'},
    {peluche:'camila', texto:'Qué lindo… yo sueño con darle un abrazo enorme 🤗'},
    {peluche:'tich', texto:'Pronto será, Camilita, paciencia 💕'},
    {peluche:'camila', texto:'Tener a papi y mami juntos sería lo mejor del mundo 😍'},
    {peluche:'tich', texto:'Y ahí estaremos nosotros, su orgullo y compañía 🧸'},
    {peluche:'camila', texto:'Siempre unidos, aunque estemos en lugares distintos 💖'},
    {peluche:'tich', texto:'Exacto, nuestro amor los mantiene cerquita 😌'},
    {peluche:'camila', texto:'Te prometo que cuando los vea, les diré todo lo que los extraño 🌸'},
    {peluche:'tich', texto:'Y yo les recordaré cuánto los queremos y admiramos 💕'},
  ],
  [
    {peluche:'tich', texto:'Camilita, hoy mami cocinó y me dijo que pensaba en ti 🍲'},
    {peluche:'camila', texto:'Awww, qué ternura, yo la extraño tanto 🥺'},
    {peluche:'tich', texto:'Ella siempre habla de lo fuerte que eres 💕'},
    {peluche:'camila', texto:'Y yo pienso en lo fuerte que es ella, siempre luchando ✨'},
    {peluche:'tich', texto:'De papi también me habló, dijo que lo extraña mucho 😢'},
    {peluche:'camila', texto:'Sí… yo extraño a papi cada día 😭'},
    {peluche:'tich', texto:'Pero también está feliz porque él estudia con mucho esfuerzo 📚'},
    {peluche:'camila', texto:'Eso me hace sentir muy orgullosa de él 😍'},
    {peluche:'tich', texto:'Papi y mami son nuestro ejemplo de amor y sacrificio 💖'},
    {peluche:'camila', texto:'Total, yo quiero ser como ellos cuando sea grande 🌟'},
    {peluche:'tich', texto:'A veces pienso que no los valoramos lo suficiente 😳'},
    {peluche:'camila', texto:'Pero sí lo hacemos, siempre hablamos bonito de ellos 💕'},
    {peluche:'tich', texto:'Entonces hay que recordárselos más seguido 🤗'},
    {peluche:'camila', texto:'Cuando los vea les daré mil abrazos y besitos 😘'},
    {peluche:'tich', texto:'Yo ya se los doy por los dos jajaja 😅'},
    {peluche:'camila', texto:'Gracias Tichito, eres el mensajero del amor 🧸'},
    {peluche:'tich', texto:'Siempre, porque papi y mami se lo merecen 💌'},
    {peluche:'camila', texto:'Estoy tan orgullosa de tenerlos como padres 💖'},
    {peluche:'tich', texto:'Yo también, son lo mejor de nuestras vidas ✨'},
    {peluche:'camila', texto:'Y aunque los extrañe, sé que estamos unidos por amor 🌸'},
  ],
  [
    {peluche:'camila', texto:'Tichito, anoche soñé que estábamos todos juntos 💭'},
    {peluche:'tich', texto:'¿De verdad? Cuéntame cómo era 😍'},
    {peluche:'camila', texto:'Mami nos abrazaba fuerte y papi reía con nosotros 🤗'},
    {peluche:'tich', texto:'Qué lindo, yo veo a mami todos los días y seguro soñaba lo mismo 💕'},
    {peluche:'camila', texto:'Es que la extraño demasiado 😭'},
    {peluche:'tich', texto:'Tranquila, yo le paso tus besitos todos los días 😘'},
    {peluche:'camila', texto:'Y papi también estaba en el sueño, nos decía que estaba orgulloso ✨'},
    {peluche:'tich', texto:'Eso seguro lo piensa en la vida real también 💖'},
    {peluche:'camila', texto:'Yo sé… aunque lo extrañe, lo admiro mucho 💪'},
    {peluche:'tich', texto:'Yo también, verlo estudiar tanto me inspira 📝'},
    {peluche:'camila', texto:'Algún día todos estaremos juntitos otra vez 🥹'},
    {peluche:'tich', texto:'Sí, ese día será el más feliz del mundo 🌟'},
    {peluche:'camila', texto:'Le diremos a mami cuánto la amamos 💕'},
    {peluche:'tich', texto:'Y a papi cuánto lo admiramos 😍'},
    {peluche:'camila', texto:'Los abrazaremos tan fuerte que nunca olviden nuestro amor 🤗'},
    {peluche:'tich', texto:'Prometido, será un abrazo eterno 💖'},
    {peluche:'camila', texto:'Qué lindo soñar con eso… me da fuerzas ✨'},
    {peluche:'tich', texto:'Y yo aquí me encargo de que mami lo sepa cada día 🌸'},
    {peluche:'camila', texto:'Gracias, Tichito, eres el mejor mensajero de mi corazón 💕'},
  ],

  // CONVERSACIONES DE CONVERSACIONES_EXTRA.JS
  [
    {peluche:'tich', texto:'Camilita, si pudieras elegir un día perfecto, ¿cómo sería? 🌟'},
    {peluche:'camila', texto:'Mmm… despertando abrazadita a ti y con papi y mami al ladito 😊'},
    {peluche:'tich', texto:'Ay, eso suena hermoso, ¿y qué hacemos después? 🤗'},
    {peluche:'camila', texto:'Tomar un desayuno junticos, todos en la mesa 🥞'},
    {peluche:'tich', texto:'Yo pediría chocolate calientico con pan 🥯'},
    {peluche:'camila', texto:'Jajaja y yo pediría pancakes con mucha miel 🍯'},
    {peluche:'tich', texto:'Después podríamos ir al parque y jugar hasta cansarnos 🎠'},
    {peluche:'camila', texto:'¡Y montarnos en todos los columpios! 🎪'},
    {peluche:'tich', texto:'Con un helado de vainilla para mí 🍦'},
    {peluche:'camila', texto:'Y uno de fresa para mí 😋🍓'},
    {peluche:'tich', texto:'Luego tomar foticos para que papi las guarde 📸'},
    {peluche:'camila', texto:'Sí, para que nunca olvide este día tan bonito 💖'},
    {peluche:'tich', texto:'Al final veríamos el atardecer sentaditos juntos 🌅'},
    {peluche:'camila', texto:'Y cenaríamos en familia, todos contentos 🍽️'},
    {peluche:'tich', texto:'Antes de dormir te contaría un cuento chistoso 📚'},
    {peluche:'camila', texto:'Y yo te llenaría de besitos hasta que te duermas 😘'},
    {peluche:'tich', texto:'Y yo te recordaría cuánto te amo 💕'},
    {peluche:'camila', texto:'Hasta dormirnos abrazaditos 🤗'},
    {peluche:'tich', texto:'Ese sí sería nuestro día perfecto 🌟'},
    {peluche:'camila', texto:'Y lo vamos a vivir, cuando papi regrese ✨'},
  ],
  [
    {peluche:'tich', texto:'Camilita, ¿qué le vamos a regalar a mami? 🎁'},
    {peluche:'camila', texto:'Yo digo que un collar bien lindo 💎'},
    {peluche:'tich', texto:'Mmm… no sé, yo prefiero un ramo de flores 🌹'},
    {peluche:'camila', texto:'¡Noo! El collar es mejor, Tich 😤'},
    {peluche:'tich', texto:'¡Nada que ver! Las flores son más especiales 😠'},
    {peluche:'camila', texto:'Pero el collar le dura para siempre 😡'},
    {peluche:'tich', texto:'Y las flores hacen que todo huela rico 😤'},
    {peluche:'camila', texto:'El collar es más elegante, caso cerrado ⚖️'},
    {peluche:'tich', texto:'¡Ay, ya no te hablo! 😡'},
    {peluche:'camila', texto:'Pues yo tampoco 😤'},
    {peluche:'tich', texto:'……'},
    {peluche:'camila', texto:'……'},
    {peluche:'tich', texto:'Camilita… y si le damos los dos, ¿ah? 😔'},
    {peluche:'camila', texto:'Mmm… está bien, me gusta la idea 😊'},
    {peluche:'tich', texto:'¡Sí! Así mami se va a sentir súper feliz 💕'},
    {peluche:'camila', texto:'Y va a decir que somos los mejores hijitos 🥰'},
    {peluche:'tich', texto:'Seguro nos llena de besitos 😄'},
    {peluche:'camila', texto:'Y de abrazos bien apretados 🤗'},
    {peluche:'tich', texto:'¡Va a ser un regalo inolvidable! ✨'},
    {peluche:'camila', texto:'Sí, porque lo hicimos juntos 💖'},
  ],
  [
    {peluche:'tich', texto:'Camilita, ¿escuchaste a Pinochito llorar? 🍼'},
    {peluche:'camila', texto:'Sí, creo que tiene hambre pobrecito 😢'},
    {peluche:'tich', texto:'Voy a prepararle su lechita 🍼'},
    {peluche:'camila', texto:'Y yo le pongo su cobijita favorita 🛌'},
    {peluche:'tich', texto:'Mira cómo sonríe cuando nos ve 😍'},
    {peluche:'camila', texto:'Es que sabe que tiene los mejores papitos 💕'},
    {peluche:'tich', texto:'Jajaja, ya se parece a ti, siempre sonriente 😊'},
    {peluche:'camila', texto:'Y a ti también, todo consentidor 😏'},
    {peluche:'tich', texto:'Pero que no se robe todos tus besitos, ¿eh? 😤'},
    {peluche:'camila', texto:'Ay Tich, celoso hasta de Pinochito 🙄'},
    {peluche:'tich', texto:'Es que te quiero solo para mí 😔'},
    {peluche:'camila', texto:'Tranquilo, mi amor, tengo besitos para los dos 😘'},
    {peluche:'tich', texto:'Bueno, pero los más grandes son para mí 💕'},
    {peluche:'camila', texto:'Jajaja, sí, no te preocupes 🤭'},
    {peluche:'tich', texto:'Pinochito ya se quedó dormidito 😴'},
    {peluche:'camila', texto:'Se ve tan tierno, parece un angelito 😍'},
    {peluche:'tich', texto:'Con ustedes siento que tengo una familia de verdad 💖'},
    {peluche:'camila', texto:'Y yo también, Tichito, somos los tres junticos 🌟'},
    {peluche:'tich', texto:'Prometamos cuidarnos siempre 🤗'},
    {peluche:'camila', texto:'Prometido, siempre los tres 💕'},
  ],
  [
    {peluche:'tich', texto:'Camilita, ¿por qué estabas tanto rato con papi? 😠'},
    {peluche:'camila', texto:'¡Porque estaba contándole algo importante! 🙄'},
    {peluche:'tich', texto:'¡Siempre es lo mismo, nunca tienes tiempo para mí! 😡'},
    {peluche:'camila', texto:'¡Ay Tich, no exageres! Yo también te dedico tiempo 😤'},
    {peluche:'tich', texto:'¡Pero a papi lo miras con esa sonrisa que debería ser mía! 😔'},
    {peluche:'camila', texto:'¡Tonto! Esa sonrisa también es tuya, no seas celoso 🙄'},
    {peluche:'tich', texto:'No quiero compartirte con nadie 😤'},
    {peluche:'camila', texto:'¡Pues yo tampoco quiero compartirte con mami! 😠'},
    {peluche:'tich', texto:'¡Eso es diferente! Mami me cuida 😒'},
    {peluche:'camila', texto:'Y papi me cuida a mí, ¿qué tiene de malo? 😤'},
    {peluche:'tich', texto:'¡Pues que siento que te pierdo! 😢'},
    {peluche:'camila', texto:'Ay Tichito… yo nunca te voy a dejar 💕'},
    {peluche:'tich', texto:'¿Lo prometes de verdad? 😔'},
    {peluche:'camila', texto:'Claro que sí, tontito mío 🤭'},
    {peluche:'tich', texto:'Es que no soporto cuando te veo tan feliz con otros 😣'},
    {peluche:'camila', texto:'Pero mi felicidad más grande eres tú 💖'},
    {peluche:'tich', texto:'¿Aunque me ponga celoso y moleste tanto? 😅'},
    {peluche:'camila', texto:'Sí, porque así eres tú y así te amo 🥰'},
    {peluche:'tich', texto:'Perdón por pelear tanto, mi amor 😔'},
    {peluche:'camila', texto:'Y yo por gritarte… ven, dame un abracito 🤗'}
  ],
  [
    {peluche:'tich', texto:'Camilita, ya no me abrazas como antes 😠'},
    {peluche:'camila', texto:'¡Claro que sí, Tichito! Pero también debo cuidar a Pinochito 🍼'},
    {peluche:'tich', texto:'¡Ajá! Siempre es "Pinochito esto, Pinochito lo otro" 😤'},
    {peluche:'camila', texto:'¡Pues es nuestro bebé! ¿Qué quieres que haga? 🙄'},
    {peluche:'tich', texto:'¡Que también pienses en mí! 😡'},
    {peluche:'camila', texto:'Ay Tich, me haces sentir como si no hiciera nada 😔'},
    {peluche:'tich', texto:'Es que te extraño… ya no eres solo mía 😢'},
    {peluche:'camila', texto:'Tonto, yo sigo siendo tuya, pero ahora somos tres 💕'},
    {peluche:'tich', texto:'No quiero que Pinochito me quite tus besitos 😒'},
    {peluche:'camila', texto:'Nadie puede quitarte mis besitos, son solo tuyos 😘'},
    {peluche:'tich', texto:'¿De verdad? 😟'},
    {peluche:'camila', texto:'De verdad, y te doy el doble si dejas los celos 🤭'},
    {peluche:'tich', texto:'Jajaja, trato hecho 😅'},
    {peluche:'camila', texto:'Ya ves, no hay razón para enojarse 💖'},
    {peluche:'tich', texto:'Perdóname por ser tan celoso 😔'},
    {peluche:'camila', texto:'Y yo por no darte tanta atención 🥺'},
    {peluche:'tich', texto:'Te amo, Camilita 💕'},
    {peluche:'camila', texto:'Y yo a ti, Tichito 🤗'},
    {peluche:'tich', texto:'Prometamos cuidar a Pinochito junticos 🍼'},
    {peluche:'camila', texto:'Sí, como la mejor familia del mundo 🌟'}
  ],

  // CONVERSACIONES DE CONVERSACIONES_FINALES.JS
  [
    {peluche:'tich', texto:'Camilita, ¡no tan duro, que nos van a escuchar! 😳'},
    {peluche:'camila', texto:'Shhh, cállate, que papi está cerca 🤫'},
    {peluche:'tich', texto:'¡Ay! Me diste un beso en la mejilla 😍'},
    {peluche:'camila', texto:'Jajaja, y si quiero darte otro, ¿qué? 😏'},
    {peluche:'tich', texto:'Pues dame, pero escondidito 🤭'},
    {peluche:'camila', texto:'Entonces ven aquí, rapidito 😘'},
    {peluche:'tich', texto:'Uy, qué traviesa eres, me vas a meter en problemas 😅'},
    {peluche:'camila', texto:'Tonto, solo si nos pillan jajaja 🙈'},
    {peluche:'tich', texto:'Ya siento que mami sospecha algo 😳'},
    {peluche:'camila', texto:'Pues que sospeche, igual nunca nos va a atrapar 😏'},
    {peluche:'tich', texto:'Oye, me sonrojé mucho 😳'},
    {peluche:'camila', texto:'Jajaja, te ves lindo así 💕'},
    {peluche:'tich', texto:'Eres mala, me haces temblar 😣'},
    {peluche:'camila', texto:'Malo tú, que no sabes decir que no 🤭'},
    {peluche:'tich', texto:'Es que no puedo resistirme a ti 💖'},
    {peluche:'camila', texto:'Awww, yo tampoco a ti 😍'},
    {peluche:'tich', texto:'Entonces… otro besito chiquito 😘'},
    {peluche:'camila', texto:'Jajaja, ya, que si no papi entra 😱'},
    {peluche:'tich', texto:'Vale, pero el último, lo prometo 🤫'},
    {peluche:'camila', texto:'Está bien… pero solo porque eres mi Tichito 💕'}
  ],
  [
    {peluche:'camila', texto:'Tich, ¿llevas la "cosita" escondida? 🙊'},
    {peluche:'tich', texto:'Sí, la tengo aquí debajo de la almohada 🤫'},
    {peluche:'camila', texto:'Jajaja, que no te la vea mami 😱'},
    {peluche:'tich', texto:'Tranquila, soy experto en guardar secretos 😏'},
    {peluche:'camila', texto:'Pues a ver cuánto aguantas sin que papi se dé cuenta 🙄'},
    {peluche:'tich', texto:'Yo puedo aguantar mucho, ¿y tú? 😏'},
    {peluche:'camila', texto:'Obvio, yo soy la mejor en disimular 🤭'},
    {peluche:'tich', texto:'Mmm… no tanto, tu carita siempre te delata 😅'},
    {peluche:'camila', texto:'¡Mentira! Yo actúo muy bien 😤'},
    {peluche:'tich', texto:'Jajaja, sí, claro… tu risa te vende 😏'},
    {peluche:'camila', texto:'¡Shhh! No te burles, bobo 🙈'},
    {peluche:'tich', texto:'Ven, dame la mano para que no me descubran 🤝'},
    {peluche:'camila', texto:'Ay, contigo siempre termino metida en problemas 😳'},
    {peluche:'tich', texto:'Pero te gusta, ¿cierto? 😏'},
    {peluche:'camila', texto:'…un poquito sí 🤭'},
    {peluche:'tich', texto:'Sabía que no podías resistirte 💕'},
    {peluche:'camila', texto:'Tonto, me haces reír demasiado 😍'},
    {peluche:'tich', texto:'Y así nadie sospecha nada 😌'},
    {peluche:'camila', texto:'Exacto… secreto bien guardado 🤫'},
  ],
  [
    {peluche:'tich', texto:'Camilita, corre, métete bajo la cobija rápido 😳'},
    {peluche:'camila', texto:'¿Qué haces? Nos van a descubrir 😱'},
    {peluche:'tich', texto:'Jajaja, es que aquí nadie nos ve 🤭'},
    {peluche:'camila', texto:'Ay Tich, siempre inventando travesuras 🙄'},
    {peluche:'tich', texto:'Pero te encanta seguirme el juego 😏'},
    {peluche:'camila', texto:'Bueno… un poquito sí 😅'},
    {peluche:'tich', texto:'Ya ves, aquí podemos hablar bajito 🤫'},
    {peluche:'camila', texto:'Y contar secretos que papi y mami no deben oír 🙊'},
    {peluche:'tich', texto:'Exacto, es nuestro escondite especial 💕'},
    {peluche:'camila', texto:'Me da risa, parecemos dos niños traviesos 🤭'},
    {peluche:'tich', texto:'Pues somos, pero también somos noviecitos 😍'},
    {peluche:'camila', texto:'Jajaja, qué atrevido 😳'},
    {peluche:'tich', texto:'Lo admito, contigo siempre me atrevo 😏'},
    {peluche:'camila', texto:'Me vas a hacer sonrojar 🙈'},
    {peluche:'tich', texto:'Eso quiero, que solo sonrías para mí 💖'},
    {peluche:'camila', texto:'Awww, tontito lindo 😍'},
    {peluche:'tich', texto:'Prometamos que nadie sepa de esto 🤫'},
    {peluche:'camila', texto:'Prometido, es nuestro secreto 💕'},
    {peluche:'tich', texto:'Entonces dame la manito aquí debajo 🤝'},
    {peluche:'camila', texto:'Listo… ahora sí somos cómplices 😘'}
  ],
  [
    {peluche:'tich', texto:'Camilita, hoy Pinochito solo quería estar contigo 😒'},
    {peluche:'camila', texto:'Ay Tichito, no te pongas celoso, yo los amo a los dos 💕'},
    {peluche:'tich', texto:'Pero a veces siento que me dejas solito 😢'},
    {peluche:'camila', texto:'Mentira, tú eres mi consentido número uno 😍'},
    {peluche:'tich', texto:'¿De verdad? 😳'},
    {peluche:'camila', texto:'Claro, tú eres mi detective favorito 🕵️‍♂️'},
    {peluche:'tich', texto:'Jajaja, entonces hoy resolvemos un caso juntos ✨'},
    {peluche:'camila', texto:'¿Cuál caso? 🤔'},
    {peluche:'tich', texto:'El misterio de los besitos robados 😘'},
    {peluche:'camila', texto:'Seguro el culpable eres tú, tramposo 🤭'},
    {peluche:'tich', texto:'Jajajaja, me descubriste 😅'},
    {peluche:'camila', texto:'Yo también tengo un caso: papi y mami son los mejores padres del mundo 💖'},
    {peluche:'tich', texto:'Ese caso está resuelto desde siempre 🌟'},
    {peluche:'camila', texto:'Aunque los extraño mucho, los siento cerca 💌'},
    {peluche:'tich', texto:'Yo estoy con mami y siempre le paso tus mensajes 😍'},
    {peluche:'camila', texto:'Gracias Tichito, eres mi enlace de amor 💕'},
    {peluche:'tich', texto:'Y también el guardián de tu corazón 😏'},
    {peluche:'camila', texto:'Entonces protégelo bien, que es tuyo 💖'},
    {peluche:'tich', texto:'Prometido, detective y enamorado siempre 🕵️‍♂️❤️'},
    {peluche:'camila', texto:'Y yo tu abogada y tu eterna enamorada 💕'}
  ],
  [
    {peluche:'tich', texto:'Camilita, Pinochito hoy no quería dormirse 😅'},
    {peluche:'camila', texto:'Jajajaja, igualito a ti, puro inquieto 🤭'},
    {peluche:'tich', texto:'Lo tuve que acunar cantándole una canción 🎵'},
    {peluche:'camila', texto:'Ay qué tierno, papi Tich 💕'},
    {peluche:'tich', texto:'¿Sabes qué me dijo en secreto? 🤫'},
    {peluche:'camila', texto:'¿Qué te dijo nuestro bebé? 😍'},
    {peluche:'tich', texto:'Que te extraña mucho y quiere abrazarte 🍼'},
    {peluche:'camila', texto:'Awwww, yo también lo extraño tanto 😭'},
    {peluche:'tich', texto:'Prometió darte mil besitos cuando te vea 💖'},
    {peluche:'camila', texto:'Lo voy a llenar de cosquillas también 🤗'},
    {peluche:'tich', texto:'Pero no te olvides de mí, que me pongo celoso 😒'},
    {peluche:'camila', texto:'Jajajaja, tú tendrás el doble de besitos 😘'},
    {peluche:'tich', texto:'Entonces trato cerrado 😏'},
    {peluche:'camila', texto:'Tichito, ¿y papi cómo está?'},
    {peluche:'tich', texto:'Trabajando y estudiando fuerte, siempre pensando en ti 💪'},
    {peluche:'camila', texto:'Lo admiro tanto, aunque lo extrañe 🥺'},
    {peluche:'tich', texto:'Yo se lo digo cada vez, y él sonríe 💕'},
    {peluche:'camila', texto:'Gracias por ser el mensajero de mi corazón 🌸'},
    {peluche:'tich', texto:'Siempre, mi abogada favorita 💖'}
  ],
  [
    {peluche:'camila', texto:'Tichito, hoy comí arepita con queso y me acordé de ti 🧀'},
    {peluche:'tich', texto:'Mmmm qué rico, yo comí con mami y estaba delicioso 😋'},
    {peluche:'camila', texto:'Yo extraño comer con ustedes 😢'},
    {peluche:'tich', texto:'Pronto será, paciencia amorcito 💕'},
    {peluche:'camila', texto:'Mientras tanto jugamos a algo por chat 😏'},
    {peluche:'tich', texto:'Vale, juguemos a "preguntas locas" 🤭'},
    {peluche:'camila', texto:'¿Quién te quiere más, yo o mami? 🙄'},
    {peluche:'tich', texto:'Ehhh… ¡empate técnico! 🤣'},
    {peluche:'camila', texto:'Tramposo, responde bien 😒'},
    {peluche:'tich', texto:'Obvio tú, mi Camila preciosa 💖'},
    {peluche:'camila', texto:'Así sí, detective fiel 😍'},
    {peluche:'tich', texto:'Pero mami también es especial, siempre cuida de mí 🌸'},
    {peluche:'camila', texto:'Lo sé, por eso la amo tanto 🥹'},
    {peluche:'tich', texto:'Y papi también, un ejemplo grande 💪'},
    {peluche:'camila', texto:'Sí, extraño sus abrazos 😭'},
    {peluche:'tich', texto:'Pronto los tendrás, Camilita ✨'},
    {peluche:'camila', texto:'Gracias, tus palabras siempre me calman 💖'},
    {peluche:'tich', texto:'Porque soy tu abracito en forma de palabras 🤗'},
    {peluche:'camila', texto:'Y yo tu sonrisa a la distancia 🌟'}
  ]
  */
];

// Función para iniciar conversaciones de peluches
function iniciarConversacionPeluches() {
  // Esta función se llama desde script.js para iniciar las conversaciones
  // La lógica principal está en script.js
  console.log('Iniciando conversaciones de peluches...');
}